Repository ipfs/kubo, pull requests merged in 2018-08, with the labels that each got.

#5322 wait for all connections to close before exiting on shutdown.
  core/commands/root.go
  core/commands/shutdown.go
  core/corehttp/corehttp.go
  test/sharness/t0023-shutdown.sh
Labels: RFM

#5313 ci: apply timeout for build steps after getting node
  ci/Jenkinsfile
Labels: RFM, ready

#5329 fix: dht findprovs unable to handle /ipfs/hash #5311
  core/commands/dht.go
  test/sharness/t0175-reprovider.sh
Labels: RFM

#5319 delete unixfs code...
  Rules.mk
  unixfs/archive/archive.go
  unixfs/archive/tar/writer.go
  unixfs/hamt/hamt.go
  unixfs/hamt/hamt_stress_test.go
  unixfs/hamt/hamt_test.go
  unixfs/hamt/util.go
  unixfs/hamt/util_test.go
  unixfs/importer/balanced/balanced_test.go
  unixfs/importer/balanced/builder.go
  unixfs/importer/helpers/dagbuilder.go
  unixfs/importer/helpers/helpers.go
  unixfs/importer/importer.go
  unixfs/importer/importer_test.go
  unixfs/importer/trickle/trickle_test.go
  unixfs/importer/trickle/trickledag.go
  unixfs/io/bufdagreader.go
  unixfs/io/dagreader.go
  unixfs/io/dagreader_test.go
  unixfs/io/directory.go
  unixfs/io/directory_test.go
  unixfs/io/doc.go
  unixfs/io/pbdagreader.go
  unixfs/io/resolve.go
  unixfs/mod/dagmodifier.go
  unixfs/mod/dagmodifier_test.go
  unixfs/pb/Rules.mk
  unixfs/pb/unixfs.pb.go
  unixfs/pb/unixfs.proto
  unixfs/test/utils.go
  unixfs/unixfs.go
  unixfs/unixfs_test.go
Labels: in progress

#5338 ci: check for gx deps dupes
  ci/Jenkinsfile
Labels: in progress

#5340 coreapi: dag: Batching interface
  core/coreapi/dag.go
  core/coreapi/dag_test.go
  core/coreapi/interface/dag.go
Labels: core-api, in progress

#5339 key cmd: Refactor to use coreapi
  core/commands/keystore.go
  core/commands/root.go
  core/coreapi/interface/key.go
  core/coreapi/key.go
  core/coreapi/key_test.go
Labels: RFM, core-api

#5285 Add ability to retrieve blocks even if given using a different CID version
  core/builder.go
  test/sharness/t0276-cidv0v1.sh
  thirdparty/cidv0v1/blockstore.go
Labels: RFM, cidv1b32, in progress

#5352 add GetSize method to the v0v1 blockstore
  thirdparty/cidv0v1/blockstore.go
Labels: RFM

#5277 Extract config package
  cmd/ipfs/Rules.mk
  cmd/ipfs/init.go
  cmd/ipfs/main.go
  cmd/ipfswatch/main.go
  commands/request.go
  core/bootstrap.go
  core/bootstrap_test.go
  core/builder.go
  core/commands/bootstrap.go
  core/commands/config.go
  core/commands/env.go
  core/commands/mount_unix.go
  core/commands/repo.go
  core/commands/swarm.go
  core/commands/sysdiag.go
  core/commands/version.go
  core/core.go
  core/core_test.go
  core/coreapi/unixfs_test.go
  core/corehttp/commands.go
  core/corehttp/gateway.go
  core/corehttp/gateway_test.go
  core/corehttp/option_test.go
  core/coreunix/add_test.go
  core/mock/mock.go
  docs/releases.md
  docs/windows.md
  package.json
  repo/config/addresses.go
  repo/config/api.go
  repo/config/bootstrap_peers.go
  repo/config/config.go
  repo/config/datastore.go
  repo/config/discovery.go
  repo/config/experiments.go
  repo/config/gateway.go
  repo/config/identity.go
  repo/config/init.go
  repo/config/ipns.go
  repo/config/mounts.go
  repo/config/profile.go
  repo/config/reprovider.go
  repo/config/routing.go
  repo/config/swarm.go
  repo/fsrepo/config_test.go
  repo/fsrepo/fsrepo.go
  repo/fsrepo/fsrepo_test.go
  repo/fsrepo/misc.go
  repo/fsrepo/serialize/serialize.go
  repo/fsrepo/serialize/serialize_test.go
  repo/mock.go
  repo/repo.go
  test/bench/bench_cli_ipfs_add/main.go
  test/bench/offline_add/main.go
  version.go
Labels: RFM

#5371 docs: add url to dev weekly sync to the README
  README.md
Labels: in progress

#5374 ci: call cleanWs after each step
  ci/Jenkinsfile
Labels: in progress

#5364 add correct test for 1515
  test/sharness/lib/test-lib.sh
  test/sharness/t0080-repo.sh
Labels: RFM

#5354 Fix some weird code in core/coreunix/add.go
  core/coreunix/add.go
Labels: core, difficulty:easy, in progress

#5373 gossipsub
  cmd/ipfs/init.go
  cmd/ipfs/main.go
  cmd/ipfswatch/main.go
  commands/request.go
  core/bootstrap.go
  core/bootstrap_test.go
  core/builder.go
  core/commands/bootstrap.go
  core/commands/config.go
  core/commands/env.go
  core/commands/mount_unix.go
  core/commands/repo.go
  core/commands/swarm.go
  core/core.go
  core/core_test.go
  core/coreapi/unixfs_test.go
  core/corehttp/commands.go
  core/corehttp/gateway_test.go
  core/coreunix/add_test.go
  core/mock/mock.go
  docs/experimental-features.md
  package.json
  repo/fsrepo/config_test.go
  repo/fsrepo/fsrepo.go
  repo/fsrepo/fsrepo_test.go
  repo/fsrepo/misc.go
  repo/mock.go
  repo/repo.go
  test/bench/bench_cli_ipfs_add/main.go
  test/bench/offline_add/main.go
  test/sharness/t0180-pubsub-gossipsub.sh
Labels: RFM

#5345 return a json object from config show
  core/commands/config.go
Labels: needs review

#5356 update protobuf files in go-ipfs
  Makefile
  Rules.mk
  filestore/fsrefstore.go
  filestore/pb/Makefile
  filestore/pb/Rules.mk
  filestore/pb/dataobj.pb.go
  filestore/pb/dataobj.proto
  filestore/util.go
  package.json
  pin/internal/pb/header.pb.go
  pin/set.go
Labels: needs review

#5384 Fixed ipns address resolution in fuse unix mount
  fuse/ipns/ipns_test.go
  fuse/ipns/ipns_unix.go
Labels: in progress

#4177 Set filename in Content-Disposition if filename=x is passed in URI query
  core/corehttp/gateway_handler.go
  test/sharness/t0110-gateway.sh
Labels: needs review

#5392 name cmd: move subcommands to subdirectory
  core/commands/add.go
  core/commands/bitswap.go
  core/commands/block.go
  core/commands/cat.go
  core/commands/cmdenv/env.go
  core/commands/dht.go
  core/commands/dns.go
  core/commands/files.go
  core/commands/filestore.go
  core/commands/get.go
  core/commands/keystore.go
  core/commands/mount_unix.go
  core/commands/name/ipns.go
  core/commands/name/ipnsps.go
  core/commands/name/name.go
  core/commands/name/publish.go
  core/commands/object/patch.go
  core/commands/p2p.go
  core/commands/ping.go
  core/commands/pubsub.go
  core/commands/repo.go
  core/commands/resolve.go
  core/commands/root.go
  core/commands/shutdown.go
  core/commands/stat.go
  core/commands/swarm.go
  core/commands/urlstore.go
Labels: in progress

#5396 docs: README refresh, add cli-http-api-core diagram
  README.md
  dev.md
  docs/cli-http-api-core-diagram.png
Labels: in progress

#5397 fix the urlstore tests
  test/sharness/t0272-urlstore.sh
Labels: in progress, needs review

#5393 add some basic gateway documentation
  docs/gateway.md
Labels: documentation, needs review

#5372 Run DNS lookup for --api endpoint provided in CLI
  cmd/ipfs/dnsresolve_test.go
  cmd/ipfs/main.go
  package.json
  test/sharness/t0236-cli-api-dns-resolve.sh
Labels: needs review

#5281 Add support for inlinling via the id-hash
  core/commands/add.go
  test/sharness/t0040-add-and-cat.sh
  test/sharness/t0046-id-hash.sh
Labels: in progress

#5337 Feat: depth limited refs -r
  core/commands/refs.go
  test/sharness/t0095-refs.sh
Labels: RFM

#5308 remove bitswap unwant
  core/commands/bitswap.go
  core/commands/commands_test.go
  misc/completion/ipfs-completion.bash
Labels: RFM

#5166 core/commands/ls: wrap `NewDirectoryFromNode` error
  core/commands/ls.go
Labels: UnixFS, documentation, files, in progress

#5409 directly parse peer IDs as peer IDs
  namesys/routing.go
  test/sharness/t0236-cli-api-dns-resolve.sh
Labels: in progress, needs review

#5414 don't bother caching if we're using a nil repo
  core/builder.go
Labels: in progress
