Repository ipfs/kubo, pull requests merged in 2018-03, with the labels that each got.

#4752 Fix "PNetFingerpint" field typo of core.IpfsNode
  cmd/ipfs/daemon.go
  core/core.go
Labels: in progress

#4770 fix pubsub pub reading stdin args
  core/commands/pubsub.go
  test/sharness/t0180-pubsub.sh
Labels: in progress

#4751 Disallow usage of unsafe hashes for reading and adding content
  blockservice/blockservice.go
  core/builder.go
  core/commands/add.go
  core/commands/pin.go
  exchange/reprovide/reprovide.go
  pin/gc/gc.go
  test/sharness/t0050-block.sh
  test/sharness/t0085-pins.sh
  test/sharness/t0275-cid-security-data/AFKSEBCGPUJZE.data
  test/sharness/t0275-cid-security.sh
  thirdparty/verifbs/verifbs.go
  thirdparty/verifcid/validate.go
  thirdparty/verifcid/validate_test.go
Labels: in progress

#4759 prepare for 0.4.14 release
  .gx/lastpubver
  CHANGELOG.md
  docs/releases.md
  package.json
  repo/config/version.go
Labels: in progress

#4772 misc: create CODEOWNERS file
  CODEOWNERS
Labels: in progress

#4790 tar: fix Go 1.10 breakage
  ci/Dockerfile.buildenv
  test/sharness/t0090-get.sh
  thirdparty/tar/extractor.go
Labels: in progress

#4813 ipfs release 0.4.14-rc2
  package.json
  repo/config/version.go
Labels: in progress

#4826 upgrade commands that used StringArguments
  core/commands/files.go
  core/commands/object/object.go
  core/commands/object/patch.go
  core/commands/root.go
Labels: in progress

#4822 fix: use EmitOnce where only single response is to be sent
  core/commands/commands.go
  core/commands/files.go
  core/commands/pubsub.go
Labels: in progress

#4827 pre-populate required arguments from request body
  cmd/ipfs/daemon.go
  cmd/ipfs/ipfs.go
  cmd/ipfs/main.go
  commands/legacy/command.go
  commands/legacy/legacy.go
  commands/legacy/legacy_test.go
  commands/legacy/request.go
  commands/legacy/response.go
  commands/request.go
  core/commands/add.go
  core/commands/bitswap.go
  core/commands/block.go
  core/commands/cat.go
  core/commands/commands.go
  core/commands/commands_test.go
  core/commands/files.go
  core/commands/filestore.go
  core/commands/get.go
  core/commands/get_test.go
  core/commands/helptext_test.go
  core/commands/object/object.go
  core/commands/object/patch.go
  core/commands/pubsub.go
  core/commands/repo.go
  core/commands/root.go
  core/commands/root_test.go
  core/commands/stat.go
  core/corehttp/commands.go
  package.json
  test/sharness/t0090-get.sh
  test/sharness/t0100-name.sh
Labels: RFM

#4840 check arguments after handling help
  cmd/ipfs/daemon.go
  cmd/ipfs/ipfs.go
  cmd/ipfs/main.go
  commands/legacy/command.go
  commands/legacy/legacy.go
  commands/legacy/legacy_test.go
  commands/legacy/request.go
  commands/legacy/response.go
  commands/request.go
  core/commands/add.go
  core/commands/bitswap.go
  core/commands/block.go
  core/commands/cat.go
  core/commands/commands.go
  core/commands/commands_test.go
  core/commands/files.go
  core/commands/filestore.go
  core/commands/get.go
  core/commands/get_test.go
  core/commands/helptext_test.go
  core/commands/object/object.go
  core/commands/object/patch.go
  core/commands/pubsub.go
  core/commands/repo.go
  core/commands/root.go
  core/commands/stat.go
  core/corehttp/commands.go
  package.json
  test/sharness/t0100-name.sh
Labels: in progress

#4836 ipfs release 0.4.14-rc3
  CHANGELOG.md
  package.json
  repo/config/version.go
Labels: in progress

#4866 Ipfs v0.4.14
  CHANGELOG.md
  package.json
  repo/config/version.go
Labels: in progress

#4563 commands/block: use CIDv1 with custom mhtype
  core/commands/block.go
  test/sharness/t0050-block.sh
Labels: RFM

#4649 blockservice: add BlockedFetched/Added/Removed events
  blockservice/blockservice.go
Labels: RFM, blockstore, tools

#4704 Feat: remove circular dependencies in merkledag package tests
  merkledag/merkledag_test.go
Labels: RFM

#4730 Refactor trickle DAG builder
  importer/trickle/trickledag.go
Labels: RFM

#4743 unixfs: clean path in DagArchive
  test/sharness/t0090-get.sh
  unixfs/archive/archive.go
Labels: RFM

#4755 add: hash-only: set the prefix for MFS root
  core/commands/add.go
  test/sharness/t0043-add-w.sh
Labels: RFM

#4767 dag: diff: check CIDs in base case when comparing nodes
  merkledag/utils/diff.go
  test/sharness/t0052-object-diff.sh
Labels: RFM

#4798 Update broken links
  contribute.md
Labels: RFM

#4802 coreapi: Split the interface into multiple files
  core/coreapi/coreapi.go
  core/coreapi/dag.go
  core/coreapi/interface/block.go
  core/coreapi/interface/coreapi.go
  core/coreapi/interface/dag.go
  core/coreapi/interface/errors.go
  core/coreapi/interface/interface.go
  core/coreapi/interface/key.go
  core/coreapi/interface/name.go
  core/coreapi/interface/object.go
  core/coreapi/interface/path.go
  core/coreapi/interface/pin.go
  core/coreapi/interface/unixfs.go
  core/coreapi/interface/util.go
  core/coreapi/object.go
  core/coreapi/unixfs.go
Labels: RFM, core-api

#4809 Fix get output path
  core/commands/get.go
Labels: RFM, in progress

#4811 bitswap: reduce level when logging about disconnected peers to info
  exchange/bitswap/wantmanager.go
Labels: RFM

#4816 Fix t0063-daemon-init.sh by adding test profile to daemon
  cmd/ipfs/daemon.go
  cmd/ipfs/init.go
  test/sharness/t0063-daemon-init.sh
Labels: RFM

#4819 misc: spelling of retrieval
  unixfs/io/dagreader.go
Labels: RFM

#4832 Use prefix in bootstrapWritePeers
  core/commands/bootstrap.go
  test/sharness/t0120-bootstrap.sh
Labels: RFM

#4834 Remove roadmap.md
  roadmap.md
Labels: RFM

#4844 fix(mfs): Directory.Path not working, add test
  mfs/dir.go
  mfs/mfs_test.go
Labels: RFM

#4848 sharness/t0010: check that all the commands fail when passed a bad flag
  test/sharness/t0010-basic-commands.sh
Labels: RFM

#4859 Fix go vet warnings
  core/builder.go
  filestore/fsrefstore.go
  repo/fsrepo/fsrepo.go
  test/dependencies/go-timeout/main.go
  thirdparty/notifier/notifier.go
Labels: RFM

#4849 No dev null pipe
  test/sharness/t0010-basic-commands.sh
Labels: RFM

#4857 Extract: thirdparty/tar
  core/commands/get.go
  package.json
  thirdparty/tar/extractor.go
Labels: RFM

#4867 misc: allow for some coverage fall on commit
  codecov.yml
Labels: needs review

#4869 bump tar dep to make it resolvable
  core/commands/get.go
  package.json
Labels: in progress

#4732 make init command use go-ipfs-cmds
  cmd/ipfs/init.go
  cmd/ipfs/ipfs.go
Labels: RFM

#4812 misc: remove link to IPFS paper in contribute.md
  contribute.md
Labels: RFM

#4792 fix incorrect Read calls
  cmd/seccat/util.go
  repo/fsrepo/fsrepo.go
  unixfs/io/pbdagreader.go
  unixfs/mod/dagmodifier.go
Labels: RFM

#4875 gx: bump version for 0.4.14 release
  .gx/lastpubver
Labels: in progress

#4856 cmds/stat: remove useless header if not polling
  core/commands/stat.go
Labels: RFM

#4154 Add low power init profile
  cmd/ipfs/daemon.go
  cmd/ipfs/init.go
  docs/config.md
  repo/config/config.go
  repo/config/init.go
  repo/config/profile.go
  repo/config/routing.go
  test/sharness/t0020-init.sh
Labels: in progress, waiting on author

#4678 build: match Go's GOPATH defaults behaviour
  bin/check_go_path
  mk/golang.mk
Labels: RFM, build

#4797 misc: add confirmation to archive-branches script
  bin/archive-branches.sh
Labels: RFM

#4873 make the tar writer handle sharded ipfs directories
  core/commands/unixfs/ls.go
  test/sharness/t0260-sharding.sh
  unixfs/archive/tar/writer.go
  unixfs/io/pbdagreader.go
Labels: RFM

#4506 Add Opentracing plugin support
  package.json
  plugin/loader/initializer.go
  plugin/tracer.go
Labels: RFM, in progress

#4865 Fix 4864
  README.md
Labels: need_signoff

#4855 Update lock
  package.json
  repo/fsrepo/lock/lock.go
Labels: RFM, dep change

#4890 infer type from CID when possible in ls command
  core/commands/ls.go
Labels: RFM

#4885 only visit nodes in EnumerateChildrenAsync when asked
  merkledag/merkledag.go
Labels: RFM

#4884 don't resolve children unnecessarily when listing a sharded directory
  test/sharness/t0260-sharding.sh
  unixfs/hamt/hamt.go
Labels: RFM

#4807 coreapi: Refactor options
  core/coreapi/block.go
  core/coreapi/block_test.go
  core/coreapi/coreapi.go
  core/coreapi/dag.go
  core/coreapi/dag_test.go
  core/coreapi/interface/block.go
  core/coreapi/interface/dag.go
  core/coreapi/interface/key.go
  core/coreapi/interface/name.go
  core/coreapi/interface/object.go
  core/coreapi/interface/options/block.go
  core/coreapi/interface/options/dag.go
  core/coreapi/interface/options/key.go
  core/coreapi/interface/options/name.go
  core/coreapi/interface/options/object.go
  core/coreapi/interface/options/pin.go
  core/coreapi/interface/pin.go
  core/coreapi/key.go
  core/coreapi/key_test.go
  core/coreapi/name.go
  core/coreapi/name_test.go
  core/coreapi/object.go
  core/coreapi/object_test.go
  core/coreapi/pin.go
  core/coreapi/pin_test.go
Labels: RFM, core-api

#4631 refactor: extract fs lock into go-fs-lock
  core/commands/repo.go
  package.json
  repo/fsrepo/fsrepo.go
  repo/fsrepo/lock/lock.go
Labels: RFM, dep change

#4829 Fix error style for most errors
  cmd/ipfs/init.go
  cmd/seccat/seccat.go
  commands/legacy/request.go
  core/commands/cat.go
  core/commands/config.go
  core/commands/dht.go
  core/commands/get.go
  core/commands/id.go
  core/commands/object/object.go
  core/commands/pin.go
  core/commands/publish.go
  core/commands/pubsub.go
  core/core.go
  core/coreapi/object.go
  core/corerepo/gc.go
  exchange/bitswap/testnet/virtual.go
  exchange/reprovide/reprovide.go
  fuse/ipns/ipns_unix.go
  fuse/mount/fuse.go
  fuse/mount/mount.go
  fuse/readonly/ipfs_test.go
  fuse/readonly/readonly_unix.go
  importer/balanced/balanced_test.go
  importer/trickle/trickle_test.go
  importer/trickle/trickledag.go
  keystore/keystore_test.go
  merkledag/coding.go
  merkledag/merkledag.go
  merkledag/merkledag_test.go
  mfs/mfs_test.go
  namesys/dns_test.go
  namesys/interface.go
  namesys/namesys_test.go
  namesys/pubsub.go
  namesys/resolve_test.go
  pin/pin.go
  repo/config/config.go
  repo/config/init.go
  repo/fsrepo/fsrepo.go
  repo/fsrepo/serialize/serialize.go
  thirdparty/pollEndpoint/main.go
  unixfs/io/pbdagreader.go
  unixfs/test/utils.go
  unixfs/unixfs.go
Labels: RFM
