Repository ipfs/kubo, pull requests merged in 2018-04, with the labels that each got.

#4903 document ipns pubsub
  docs/experimental-features.md
Labels: RFM

#4889 improve performance of HAMTs
  package.json
  unixfs/hamt/hamt.go
  unixfs/hamt/hamt_test.go
  unixfs/hamt/util.go
  unixfs/hamt/util_test.go
Labels: RFM

#4846 Fix missing profile docs
  cmd/ipfs/init.go
  core/commands/config.go
  repo/config/profile.go
Labels: RFM

#4888 dedup keys in GetMany
  merkledag/merkledag.go
  merkledag/merkledag_test.go
Labels: RFM

#4845 fix default-net profile not reverting bootstrap config
  repo/config/profile.go
  test/sharness/t0021-config.sh
Labels: RFM, in progress

#4940 dag: deduplicate AddNodeLinkClean into AddNodeLink
  core/coreunix/metadata.go
  importer/helpers/helpers.go
  merkledag/merkledag_test.go
  merkledag/node.go
  merkledag/utils/utils.go
  pin/pin_test.go
  pin/set_test.go
  tar/format.go
  unixfs/io/dirbuilder.go
  unixfs/mod/dagmodifier.go
Labels: RFM

#4835 misc: Fix a few typos
  CHANGELOG.md
  README.md
  bin/dist_get
  cmd/ipfs/init.go
  cmd/ipfs/main.go
  cmd/ipfs/util/ulimit_freebsd.go
  cmd/seccat/seccat.go
  commands/request.go
  contribute.md
  core/builder.go
  core/commands/add.go
  core/commands/block.go
  core/commands/dag/dag.go
  core/commands/mount_unix.go
  core/commands/refs.go
  core/coreapi/coreapi.go
  core/coreapi/interface/options/pin.go
  core/coredag/dagtransl.go
  core/corerepo/pinning.go
  core/pathresolver.go
  docs/experimental-features.md
  docs/file-transfer.md
  docs/releases.md
  exchange/bitswap/README.md
  exchange/bitswap/bitswap.go
  exchange/bitswap/decision/ledger.go
  importer/helpers/dagbuilder.go
  importer/trickle/trickledag.go
  merkledag/raw.go
  namesys/pubsub.go
  pin/pin.go
  pin/set.go
  plugin/plugin.go
  repo/fsrepo/fsrepo.go
  repo/fsrepo/migrations/mfsr_test.go
  repo/fsrepo/migrations/migrations.go
  test/sharness/README.md
  thirdparty/dir/dir.go
  unixfs/mod/dagmodifier.go
Labels: RFM

#4943 github: remove go-ipfs version from issue template
  ISSUE_TEMPLATE.md
Labels: RFM

#4933 Fix typo in error message
  repo/fsrepo/fsrepo.go
Labels: RFM

#4833 misc: Remove some dead code
  cmd/ipfs/main.go
  commands/legacy/responseemitter.go
  core/commands/dag/dag.go
  core/commands/filestore.go
  core/commands/object/object.go
  core/commands/pin.go
  core/core.go
  core/coreunix/add.go
  exchange/bitswap/bitswap.go
  exchange/bitswap/testutils.go
  fuse/ipns/writerat.go
  importer/helpers/helpers.go
  importer/importer.go
  merkledag/merkledag.go
  path/path.go
  path/path_test.go
  test/api-startup/main.go
  unixfs/archive/archive.go
  unixfs/archive/tar/writer.go
Labels: RFM

#4920 mk: add tarball support
  .gitignore
  Rules.mk
  bin/maketarball.sh
  cmd/ipfs/Rules.mk
  mk/git.mk
  mk/gx.mk
  mk/tarball.mk
Labels: RFM, build

#4955 fix unused imports
  core/coreunix/add.go
Labels: in progress

#4971 gx: remove unused lock dep
  package.json
Labels: RFM

#4691 Change Windows build documentation
  docs/windows.md
Labels: in progress

#4975 gx: update go-ipfs-cmds
  cmd/ipfs/daemon.go
  cmd/ipfs/init.go
  cmd/ipfs/ipfs.go
  cmd/ipfs/main.go
  commands/legacy/command.go
  commands/legacy/legacy.go
  commands/legacy/legacy_test.go
  commands/legacy/request.go
  commands/legacy/response.go
  commands/request.go
  core/commands/add.go
  core/commands/bitswap.go
  core/commands/block.go
  core/commands/cat.go
  core/commands/commands.go
  core/commands/commands_test.go
  core/commands/files.go
  core/commands/filestore.go
  core/commands/get.go
  core/commands/get_test.go
  core/commands/helptext_test.go
  core/commands/object/object.go
  core/commands/object/patch.go
  core/commands/pubsub.go
  core/commands/repo.go
  core/commands/root.go
  core/commands/stat.go
  core/corehttp/commands.go
  package.json
Labels: in progress

#4872 gx: update go-ds-flatfs
  package.json
  repo/fsrepo/datastores.go
Labels: in progress

#4972 Ipfs 0.4.15-rc1
  CHANGELOG.md
  package.json
  repo/config/version.go
Labels: in progress

#4983 gx: release 0.4.15-rc1
  .gx/lastpubver
Labels: in progress
