Repository ipfs/kubo, pull requests merged in 2018-12, with the labels that each got.

#4636 merge github-issue-guide with the issue template
  ISSUE_TEMPLATE.md
  docs/github-issue-guide.md
Labels: in progress

#5751 block: rm extra output
  core/commands/block.go
  test/sharness/t0050-block.sh
Labels: RFM, in progress

#5832 README: document guix package
  README.md
Labels: in progress

#5048 Really run as non-root user in docker container
  Dockerfile
  Dockerfile.fast
Labels: containers + vms, in progress

#5834 add pinning support to the urlstore
  core/commands/urlstore.go
  test/sharness/t0272-urlstore.sh
Labels: in progress

#5839 config: document the connection manager
  docs/config.md
Labels: documentation, in progress

#5801 add --dereference-args parameter
  cmd/ipfs/daemon.go
  cmd/ipfs/init.go
  cmd/ipfs/ipfs.go
  cmd/ipfs/main.go
  commands/context.go
  core/commands/active.go
  core/commands/add.go
  core/commands/bitswap.go
  core/commands/block.go
  core/commands/bootstrap.go
  core/commands/cat.go
  core/commands/cid.go
  core/commands/cmdenv/env.go
  core/commands/commands.go
  core/commands/commands_test.go
  core/commands/config.go
  core/commands/dag/dag.go
  core/commands/dht.go
  core/commands/diag.go
  core/commands/dns.go
  core/commands/external.go
  core/commands/files.go
  core/commands/filestore.go
  core/commands/get.go
  core/commands/get_test.go
  core/commands/helptext_test.go
  core/commands/id.go
  core/commands/keystore.go
  core/commands/log.go
  core/commands/ls.go
  core/commands/mount_nofuse.go
  core/commands/mount_unix.go
  core/commands/mount_windows.go
  core/commands/name/ipns.go
  core/commands/name/ipnsps.go
  core/commands/name/name.go
  core/commands/name/publish.go
  core/commands/object/diff.go
  core/commands/object/object.go
  core/commands/object/patch.go
  core/commands/p2p.go
  core/commands/pin.go
  core/commands/ping.go
  core/commands/pubsub.go
  core/commands/refs.go
  core/commands/repo.go
  core/commands/resolve.go
  core/commands/root.go
  core/commands/shutdown.go
  core/commands/stat.go
  core/commands/swarm.go
  core/commands/sysdiag.go
  core/commands/tar.go
  core/commands/unixfs/ls.go
  core/commands/unixfs/unixfs.go
  core/commands/urlstore.go
  core/commands/version.go
  core/corehttp/commands.go
  package.json
  test/sharness/t0040-add-and-cat.sh
Labels: in progress

#5844 startup: always load the private key
  cmd/ipfs/init.go
  core/builder.go
  core/commands/cat.go
  core/commands/id.go
  core/commands/resolve.go
  core/core.go
  core/coreapi/name.go
  core/coreapi/unixfs_test.go
  fuse/ipns/ipns_test.go
  fuse/node/mount_test.go
Labels: in progress

#4806 Stateful plugin loading
  cmd/ipfs/main.go
  commands/context.go
  plugin/loader/initializer.go
  plugin/loader/load.go
  plugin/loader/loader.go
  repo/fsrepo/config_test.go
Labels: in progress

#5857 gx: update pubsub, connmgr, and flatfs
  core/core.go
  core/coreapi/pubsub.go
  package.json
  plugin/plugins/flatfs/flatfs.go
Labels: in progress

#5825 CoreAPI: Global offline option
  cmd/ipfs/daemon.go
  commands/context.go
  core/commands/add.go
  core/commands/block.go
  core/commands/cat.go
  core/commands/cmdenv/env.go
  core/commands/files.go
  core/commands/keystore.go
  core/commands/ls.go
  core/commands/name/ipns.go
  core/commands/name/publish.go
  core/commands/object/diff.go
  core/commands/object/object.go
  core/commands/object/patch.go
  core/commands/pin.go
  core/commands/pubsub.go
  core/commands/resolve.go
  core/commands/root.go
  core/commands/swarm.go
  core/commands/unixfs/ls.go
  core/core.go
  core/coreapi/block.go
  core/coreapi/coreapi.go
  core/coreapi/dht.go
  core/coreapi/interface/coreapi.go
  core/coreapi/interface/options/global.go
  core/coreapi/interface/options/name.go
  core/coreapi/interface/options/unixfs.go
  core/coreapi/key.go
  core/coreapi/name.go
  core/coreapi/object.go
  core/coreapi/path.go
  core/coreapi/pin.go
  core/coreapi/pubsub.go
  core/coreapi/swarm.go
  core/coreapi/unixfs.go
  core/coreapi/unixfs_test.go
  core/corehttp/gateway.go
  core/corerepo/pinning.go
  core/coreunix/add.go
  fuse/readonly/ipfs_test.go
  test/integration/addcat_test.go
  test/integration/bench_cat_test.go
  test/integration/three_legged_cat_test.go
Labels: RFM, core-api, in progress

#5634 fix config data race
  cmd/ipfs/init.go
  cmd/ipfs/main.go
  cmd/ipfswatch/main.go
  commands/context.go
  core/bootstrap.go
  core/bootstrap_test.go
  core/builder.go
  core/commands/bootstrap.go
  core/commands/cmdenv/env.go
  core/commands/config.go
  core/commands/mount_unix.go
  core/commands/repo.go
  core/commands/swarm.go
  core/core.go
  core/core_test.go
  core/coreapi/unixfs_test.go
  core/corehttp/commands.go
  core/corehttp/gateway_test.go
  core/coreunix/add_test.go
  core/mock/mock.go
  package.json
  repo/fsrepo/config_test.go
  repo/fsrepo/fsrepo.go
  repo/fsrepo/fsrepo_test.go
  repo/fsrepo/misc.go
  repo/mock.go
  repo/repo.go
  test/bench/bench_cli_ipfs_add/main.go
  test/bench/offline_add/main.go
  test/dependencies/iptb/iptb.go
Labels: in progress

#5860 make: fix building source tarball on macos
  bin/maketarball.sh
Labels: in progress

#5871 gx: update progress bar
  core/commands/add.go
  core/commands/get.go
  package.json
Labels: in progress

#5872 main: move InterruptHandler to util
  cmd/ipfs/main.go
  cmd/ipfs/util/signal.go
  cmd/ipfs/util/signal_wasm.go
Labels: in progress

#5876 docs: flesh out plugin documentation
  docs/plugins.md
Labels: in progress
