Repository ipfs/kubo, pull requests merged in 2018-06, with the labels that each got.

#5068 fix the duplicate (multiple versions) sys import
  cmd/ipfswatch/main.go
  fuse/ipns/ipns_test.go
  fuse/ipns/ipns_unix.go
  fuse/ipns/link_unix.go
  fuse/mount/fuse.go
  fuse/readonly/ipfs_test.go
  fuse/readonly/readonly_unix.go
  package.json
Labels: in progress

#5079 embed public keys inside ipns records, use for validation
  namesys/ipns_validate_test.go
  namesys/pb/namesys.pb.go
  namesys/pb/namesys.proto
  namesys/publisher.go
  namesys/validator.go
Labels: in progress

#5075 update multiplexers
  blockservice/test/mock.go
  core/bootstrap.go
  core/commands/dht.go
  core/commands/id.go
  core/commands/ipns.go
  core/commands/pubsub.go
  core/commands/swarm.go
  core/core.go
  core/coreapi/name.go
  core/corehttp/gateway.go
  core/corehttp/gateway_test.go
  core/corehttp/metrics_test.go
  core/mock/mock.go
  exchange/bitswap/bitswap_test.go
  exchange/bitswap/network/ipfs_impl.go
  exchange/bitswap/testnet/network_test.go
  exchange/bitswap/testnet/peernet.go
  exchange/bitswap/testnet/virtual.go
  exchange/bitswap/testutils.go
  exchange/reprovide/reprovide_test.go
  fuse/ipns/ipns_test.go
  fuse/node/mount_test.go
  namesys/ipns_validate_test.go
  namesys/namesys_test.go
  namesys/publisher_test.go
  namesys/republisher/repub_test.go
  namesys/resolve_test.go
  namesys/routing.go
  p2p/p2p.go
  package.json
  repo/config/bootstrap_peers.go
  test/integration/addcat_test.go
  test/integration/bench_cat_test.go
  test/integration/bitswap_wo_routing_test.go
  test/integration/three_legged_cat_test.go
Labels: RFM

#4817 transport refactor update
  blockservice/test/mock.go
  cmd/ipfs/daemon.go
  cmd/ipfs/main.go
  cmd/seccat/seccat.go
  cmd/seccat/util.go
  core/bootstrap.go
  core/bootstrap_test.go
  core/builder.go
  core/commands/dht.go
  core/commands/id.go
  core/commands/ipns.go
  core/commands/ping.go
  core/commands/pubsub.go
  core/commands/stat.go
  core/commands/swarm.go
  core/commands/sysdiag.go
  core/core.go
  core/coreapi/name.go
  core/corehttp/corehttp.go
  core/corehttp/gateway.go
  core/corehttp/gateway_handler.go
  core/corehttp/gateway_test.go
  core/corehttp/metrics_test.go
  core/mock/mock.go
  exchange/bitswap/bitswap_test.go
  exchange/bitswap/message/message.go
  exchange/bitswap/network/interface.go
  exchange/bitswap/network/ipfs_impl.go
  exchange/bitswap/testnet/network_test.go
  exchange/bitswap/testnet/peernet.go
  exchange/bitswap/testnet/virtual.go
  exchange/bitswap/testutils.go
  exchange/reprovide/reprovide.go
  exchange/reprovide/reprovide_test.go
  fuse/ipns/ipns_test.go
  fuse/node/mount_test.go
  namesys/ipns_validate_test.go
  namesys/namesys.go
  namesys/namesys_test.go
  namesys/publisher.go
  namesys/publisher_test.go
  namesys/republisher/repub_test.go
  namesys/resolve_test.go
  namesys/routing.go
  namesys/validator.go
  p2p/p2p.go
  p2p/registry.go
  package.json
  repo/config/bootstrap_peers.go
  test/dependencies/ma-pipe-unidir/main.go
  test/integration/addcat_test.go
  test/integration/bench_cat_test.go
  test/integration/bitswap_wo_routing_test.go
  test/integration/three_legged_cat_test.go
  thirdparty/pollEndpoint/main.go
Labels: RFM

#4693 Create a raw node instead of a file node when there is no content.
  importer/balanced/builder.go
  importer/helpers/dagbuilder.go
  test/sharness/t0040-add-and-cat.sh
Labels: in progress, needs review

#5069 cat iptb logs on iptb failure (for debugging CI)
  test/sharness/lib/iptb-lib.sh
Labels: in progress

#5107 improve swarm connect/disconnect commands
  core/commands/swarm.go
  package.json
  repo/config/bootstrap_peers.go
  test/sharness/t0140-swarm.sh
Labels: needs review

#5091 reduce log level when we can't republish
  namesys/republisher/repub.go
Labels: in progress

#5119 disable the MacOS tests in jenkins
  ci/Jenkinsfile
Labels: RFM

#5124 extract ipns record logic to go-ipns
  Rules.mk
  core/commands/dht_test.go
  core/core.go
  namesys/ipns_resolver_validation_test.go
  namesys/ipns_select_test.go
  namesys/pb/Rules.mk
  namesys/pb/namesys.pb.go
  namesys/pb/namesys.proto
  namesys/publisher.go
  namesys/publisher_test.go
  namesys/republisher/repub.go
  namesys/resolve_test.go
  namesys/routing.go
  namesys/validator.go
  package.json
Labels: in progress, needs review

#5122 Fix how filestore is hooked up.
  core/builder.go
Labels: RFM

#5125 make republisher test robust against timing issues
  namesys/republisher/repub_test.go
Labels: in progress

#5071 ci: Archive sharness trash dirs
  ci/Jenkinsfile
Labels: in progress

#5144 explicitly import go-multiaddr-dns in config/bootstrap_peers
  repo/config/bootstrap_peers.go
Labels: RFM

#5116 add record validation to offline routing
  blockservice/test/mock.go
  core/builder.go
  core/commands/dht_test.go
  core/commands/ipns.go
  core/core.go
  core/coreapi/name.go
  exchange/bitswap/bitswap_test.go
  exchange/bitswap/testnet/network_test.go
  exchange/bitswap/testnet/peernet.go
  exchange/bitswap/testnet/virtual.go
  exchange/reprovide/reprovide_test.go
  fuse/ipns/ipns_test.go
  fuse/node/mount_test.go
  namesys/ipns_resolver_validation_test.go
  namesys/namesys_test.go
  namesys/publisher.go
  namesys/publisher_test.go
  namesys/republisher/repub.go
  namesys/resolve_test.go
  namesys/routing.go
  package.json
Labels: RFM

#5114 fixup DHT sharness tests
  test/sharness/t0170-dht.sh
Labels: needs review

#5159 Ipfs v0.4.16-rc1
  CHANGELOG.md
  package.json
  repo/config/version.go
Labels: in progress

#5167 add: use file name instead of path name
  core/coreunix/add.go
  core/coreunix/add_test.go
  core/coreunix/test/data/colors/orange
  core/coreunix/test/data/corps/apple
  core/coreunix/test/data/fruits/apple
  core/coreunix/test/data/fruits/orange
Labels: RFM

#5164 Grammar fix
  docs/fuse.md
Labels: RFM
