Repository ipfs/kubo, pull requests merged in 2018-10, with the labels that each got.

#5492 Cleanup instances of manual resolver construction
  core/commands/cat.go
  core/commands/files.go
  core/commands/ls.go
  core/commands/pin.go
  core/commands/unixfs/ls.go
  core/coreapi/interface/util.go
  core/coreapi/pin.go
  core/corerepo/pinning.go
  core/coreunix/cat.go
  core/pathresolver.go
  fuse/readonly/ipfs_test.go
  test/integration/addcat_test.go
  test/integration/bench_cat_test.go
  test/integration/three_legged_cat_test.go
Labels: core-api, in progress

#5546 debug-guide.md added memory statistics command
  docs/debug-guide.md
Labels: documentation

#5506 add pin lock in AddallPin function
  core/commands/add.go
  core/coreunix/add.go
  core/coreunix/add_test.go
Labels: in progress

#5385 Provide new "cid" sub-command.
  cmd/ipfs/ipfs.go
  core/commands/cid.go
  core/commands/commands.go
  core/commands/commands_test.go
  core/commands/filestore.go
  core/commands/root.go
  test/sharness/t0290-cid.sh
Labels: cidv1b32, in progress

#5550 take the pinlock when updating pins
  core/coreapi/pin.go
Labels: in progress

#5509 Add sessions when fetching MerkleDAG in LS
  core/commands/ls.go
Labels: in progress

#5472 fix(object): add support for raw leaves in object diff
  dagutils/diff.go
  test/sharness/t0052-object-diff.sh
Labels: in progress, needs review

#5563 Switch name publish/resolve to coreapi
  core/commands/name/ipns.go
  core/commands/name/publish.go
  core/coreapi/interface/options/name.go
  core/coreapi/key.go
  core/coreapi/name.go
Labels: core-api, in progress

#5533 add dns support in`ipfs p2p forward` and refactor code
  core/commands/p2p.go
  test/sharness/t0180-p2p.sh
Labels: in progress

#5187 Add support for datastore plugins
  plugin/datastore.go
  plugin/loader/initializer.go
  repo/fsrepo/datastores.go
Labels: in progress

#5501 Refactor UnixFS CoreAPI
  core/commands/add.go
  core/commands/tar.go
  core/coreapi/interface/options/unixfs.go
  core/coreapi/interface/unixfs.go
  core/coreapi/name_test.go
  core/coreapi/pin_test.go
  core/coreapi/unixfile.go
  core/coreapi/unixfs.go
  core/coreapi/unixfs_test.go
  core/corehttp/gateway_handler.go
  core/coreunix/add.go
  core/coreunix/add_test.go
Labels: core-api, in progress

#4805 coreapi: PubSub API
  core/commands/pubsub.go
  core/coreapi/coreapi.go
  core/coreapi/interface/coreapi.go
  core/coreapi/interface/errors.go
  core/coreapi/interface/options/pubsub.go
  core/coreapi/interface/pubsub.go
  core/coreapi/pubsub.go
  core/coreapi/pubsub_test.go
  core/coreapi/unixfs_test.go
Labels: core-api, in progress

#5483 switch to go 1.11
  .travis.yml
  Dockerfile
  Dockerfile.fast
  bin/Rules.mk
  ci/Dockerfile.buildenv
  ci/Jenkinsfile
  circle.yml
  cmd/ipfs/daemon.go
  mk/golang.mk
  package.json
Labels: in progress

#5575 fix: maketarball.sh for OSX
  bin/maketarball.sh
Labels: in progress

#5580 test the correct return value
  test/sharness/lib/test-lib.sh
Labels: RFM

#5596 downgrade iptb to a 1.3 patch release
  package.json
Labels: in progress

#5607 Change to point to combined go contributing guidelines
  CONTRIBUTING.md
  contribute.md
Labels: in progress

#5605 fix(files): add slash for dir
  core/commands/files.go
  test/sharness/t0250-files-api.sh
Labels: RFM, commands, files

#5404 ipfs name resolve --stream
  core/commands/name/ipns.go
  core/core.go
  core/coreapi/interface/name.go
  core/coreapi/name.go
  core/corehttp/gateway_test.go
  namesys/base.go
  namesys/dns.go
  namesys/interface.go
  namesys/ipns_resolver_validation_test.go
  namesys/namesys.go
  namesys/namesys_test.go
  namesys/opts/opts.go
  namesys/proquint.go
  namesys/routing.go
  test/sharness/t0100-name.sh
  test/sharness/t0183-namesys-pubsub.sh
Labels: in progress

#5586 fix: sharness race in directory_size if file is removed
  test/sharness/lib/test-lib.sh
  test/sharness/t0080-repo.sh
Labels: in progress

#5574 coreapi unixfs: remove Cat, use sessions
  core/commands/cat.go
  core/coreapi/coreapi.go
  core/coreapi/dag.go
  core/coreapi/interface/unixfs.go
  core/coreapi/object.go
  core/coreapi/path.go
  core/coreapi/pin.go
  core/coreapi/unixfile.go
  core/coreapi/unixfs.go
  core/coreapi/unixfs_test.go
  core/corehttp/gateway_handler.go
  fuse/readonly/ipfs_test.go
  test/integration/addcat_test.go
  test/integration/bench_cat_test.go
  test/integration/three_legged_cat_test.go
Labels: core-api, in progress

#5627 update webui to 2.1.0
  core/corehttp/webui.go
Labels: in progress

#5617 docs: Update link format
  CONTRIBUTING.md
Labels: RFM

#5455 feat: add dry-run flag for config profile apply command
  core/commands/config.go
  package.json
  test/sharness/t0021-config.sh
Labels: RFM, in progress, security

#5645 remove p2p-circuit addr hack in ipfs swarm peers
  core/commands/swarm.go
Labels: in progress

#5647 configurable pubsub signing
  cmd/ipfs/init.go
  cmd/ipfs/main.go
  cmd/ipfswatch/main.go
  commands/request.go
  core/bootstrap.go
  core/bootstrap_test.go
  core/builder.go
  core/commands/bootstrap.go
  core/commands/cmdenv/env.go
  core/commands/config.go
  core/commands/mount_unix.go
  core/commands/repo.go
  core/commands/swarm.go
  core/core.go
  core/core_test.go
  core/coreapi/pubsub.go
  core/coreapi/unixfs_test.go
  core/corehttp/commands.go
  core/corehttp/gateway_test.go
  core/coreunix/add_test.go
  core/mock/mock.go
  package.json
  repo/fsrepo/config_test.go
  repo/fsrepo/fsrepo.go
  repo/fsrepo/fsrepo_test.go
  repo/fsrepo/misc.go
  repo/mock.go
  repo/repo.go
  test/bench/bench_cli_ipfs_add/main.go
  test/bench/offline_add/main.go
  test/sharness/t0180-pubsub.sh
Labels: in progress

#5656 gx: update pubsub (again)
  core/core.go
  core/coreapi/pubsub.go
  package.json
Labels: in progress

#5653 gx: update go-ipfs-cmds
  cmd/ipfs/daemon.go
  cmd/ipfs/init.go
  cmd/ipfs/ipfs.go
  cmd/ipfs/main.go
  commands/legacy/command.go
  commands/legacy/legacy.go
  commands/legacy/legacy_test.go
  commands/legacy/request.go
  commands/legacy/response.go
  commands/request.go
  core/commands/add.go
  core/commands/bitswap.go
  core/commands/block.go
  core/commands/cat.go
  core/commands/cid.go
  core/commands/cmdenv/env.go
  core/commands/commands.go
  core/commands/commands_test.go
  core/commands/files.go
  core/commands/filestore.go
  core/commands/get.go
  core/commands/get_test.go
  core/commands/helptext_test.go
  core/commands/id.go
  core/commands/keystore.go
  core/commands/name/ipns.go
  core/commands/name/ipnsps.go
  core/commands/name/name.go
  core/commands/name/publish.go
  core/commands/object/object.go
  core/commands/object/patch.go
  core/commands/pubsub.go
  core/commands/repo.go
  core/commands/resolve.go
  core/commands/root.go
  core/commands/shutdown.go
  core/commands/stat.go
  core/commands/swarm.go
  core/commands/urlstore.go
  core/corehttp/commands.go
  package.json
Labels: in progress

#5660 namesys: properly attach path in name.Resolve
  core/coreapi/name_test.go
  namesys/namesys.go
Labels: in progress, regression

#5670 gx: update go-ipfs-cmds to 2.0.5
  cmd/ipfs/daemon.go
  cmd/ipfs/init.go
  cmd/ipfs/ipfs.go
  cmd/ipfs/main.go
  commands/legacy/command.go
  commands/legacy/legacy.go
  commands/legacy/legacy_test.go
  commands/legacy/request.go
  commands/legacy/response.go
  commands/request.go
  core/commands/add.go
  core/commands/bitswap.go
  core/commands/block.go
  core/commands/cat.go
  core/commands/cid.go
  core/commands/cmdenv/env.go
  core/commands/commands.go
  core/commands/commands_test.go
  core/commands/dag/dag.go
  core/commands/dns.go
  core/commands/files.go
  core/commands/filestore.go
  core/commands/get.go
  core/commands/get_test.go
  core/commands/helptext_test.go
  core/commands/id.go
  core/commands/keystore.go
  core/commands/name/ipns.go
  core/commands/name/ipnsps.go
  core/commands/name/name.go
  core/commands/name/publish.go
  core/commands/object/object.go
  core/commands/object/patch.go
  core/commands/pubsub.go
  core/commands/repo.go
  core/commands/resolve.go
  core/commands/root.go
  core/commands/shutdown.go
  core/commands/stat.go
  core/commands/swarm.go
  core/commands/tar.go
  core/commands/urlstore.go
  core/commands/version.go
  core/corehttp/commands.go
  package.json
Labels: in progress

#5667 simplify dag put and correctly take pin lock
  core/commands/dag/dag.go
Labels: in progress

#5688 gx: update pubsub
  core/core.go
  core/coreapi/pubsub.go
  package.json
Labels: in progress

#5689 flesh out changelog with changes in sub-packages
  CHANGELOG.md
Labels: in progress

#5692 Tweaks to "CIDv1/Base32 Migration" section in 0.4.18 release notes.
  CHANGELOG.md
Labels: in progress

#5693 changelog: summary for 0.4.18 `ipfs p2p` changes
  CHANGELOG.md
Labels: in progress

#5691 Use CircleCI 2.0
  .circleci/config.yml
  Rules.mk
  bin/circle.sh
  circle.yml
  coverage/Rules.mk
  test/Rules.mk
  test/bin/Rules.mk
  test/dependencies/json-to-junit/main.go
  test/unit/.gitignore
  test/unit/Rules.mk
Labels: in progress

#5680 cleanup the ping command
  core/commands/ping.go
  test/sharness/t0041-ping.sh
Labels: in progress

#5697 commands: fix a bunch of tiny commands-lib issues
  core/commands/dag/dag.go
  core/commands/dns.go
  core/commands/pubsub.go
  core/commands/stat.go
  core/commands/tar.go
  core/commands/version.go
Labels: in progress

#5698 ping: switch to the ping service enabled in the libp2p constructor
  core/commands/ping.go
  core/core.go
Labels: in progress

#5699 Fix pin ls output when hash is specified
  core/commands/pin.go
  test/sharness/t0085-pins.sh
Labels: in progress

#5700 coreapi: fix errisdir
  core/coreapi/interface/errors.go
Labels: in progress

#5701 gx: update go-path
  core/builder.go
  core/commands/dag/dag.go
  core/commands/dht.go
  core/commands/files.go
  core/commands/get.go
  core/commands/name/ipns.go
  core/commands/refs.go
  core/commands/resolve.go
  core/commands/tar.go
  core/core.go
  core/coreapi/interface/path.go
  core/coreapi/key.go
  core/coreapi/name.go
  core/coreapi/name_test.go
  core/coreapi/path.go
  core/coreapi/unixfs.go
  core/corehttp/commands.go
  core/corehttp/gateway_handler.go
  core/corehttp/gateway_test.go
  core/corerepo/gc.go
  core/coreunix/add.go
  core/pathresolver.go
  core/pathresolver_test.go
  dagutils/utils.go
  dagutils/utils_test.go
  fuse/ipns/common.go
  fuse/ipns/ipns_unix.go
  fuse/readonly/readonly_unix.go
  namesys/base.go
  namesys/cache.go
  namesys/dns.go
  namesys/interface.go
  namesys/ipns_resolver_validation_test.go
  namesys/namesys.go
  namesys/namesys_test.go
  namesys/proquint.go
  namesys/publisher.go
  namesys/republisher/repub.go
  namesys/republisher/repub_test.go
  namesys/resolve_test.go
  namesys/routing.go
  package.json
  tar/format.go
Labels: in progress

#5705 error on resolving non-terminal paths
  core/commands/resolve.go
  test/sharness/t0160-resolve.sh
Labels: in progress

#5708 re-format log output as ndjson
  core/commands/log.go
Labels: in progress

#5706 fix prometheus concurrent map write bug
  cmd/ipfs/daemon.go
  core/corehttp/metrics.go
  package.json
Labels: in progress
