Repository ipfs/kubo, pull requests merged in 2018-09, with the labels that each got.

#5419 fix the default gateway port
  docs/gateway.md
Labels: in progress

#5428 add missing link to the QUIC experiment
  docs/experimental-features.md
Labels: RFM

#5437 docs: add some minimal read-only API documentation
  docs/gateway.md
Labels: documentation, in progress

#5395 feat: use package-table
  README.md
  package-list.json
Labels: backlog, documentation, in progress, needs review

#5331 block cmd: Use coreapi
  core/commands/block.go
  core/coreapi/block.go
  core/coreapi/block_test.go
  core/coreapi/interface/block.go
  core/coreapi/interface/options/block.go
  core/coreapi/path_test.go
Labels: RFM, core-api

#4804 coreapi: DHT API
  core/coreapi/coreapi.go
  core/coreapi/dht.go
  core/coreapi/dht_test.go
  core/coreapi/interface/coreapi.go
  core/coreapi/interface/dht.go
  core/coreapi/interface/options/dht.go
  core/coreapi/name_test.go
  core/coreapi/unixfs_test.go
  exchange/reprovide/providers.go
Labels: RFM, core-api, in progress

#5445 add warning when no bootstrap in config
  core/bootstrap.go
Labels: waiting on author

#5433 improve gateway options test
  core/corehttp/gateway_test.go
Labels: RFM

#5459 fix output of object command
  core/commands/object/object.go
  test/sharness/t0051-object.sh
Labels: in progress

#5440 remove Godeps
  Godeps/Godeps.json
  Godeps/_workspace/src/github.com/hashicorp/golang-lru/.gitignore
  Godeps/_workspace/src/github.com/hashicorp/golang-lru/LICENSE
  Godeps/_workspace/src/github.com/hashicorp/golang-lru/README.md
  Godeps/_workspace/src/github.com/hashicorp/golang-lru/lru.go
  Godeps/_workspace/src/github.com/hashicorp/golang-lru/lru_test.go
  Godeps/_workspace/src/github.com/jbenet/go-random-files/LICENSE
  Godeps/_workspace/src/github.com/jbenet/go-random-files/Makefile
  Godeps/_workspace/src/github.com/jbenet/go-random-files/README.md
  Godeps/_workspace/src/github.com/jbenet/go-random-files/lib.go
  Godeps/_workspace/src/github.com/jbenet/go-random-files/random-files/.gitignore
  Godeps/_workspace/src/github.com/jbenet/go-random-files/random-files/README.md
  Godeps/_workspace/src/github.com/jbenet/go-random-files/random-files/main.go
  Godeps/_workspace/src/github.com/jbenet/go-random-files/ringreader/ringreader.go
  Godeps/_workspace/src/github.com/jbenet/go-random-files/ringreader/ringreader_test.go
  Godeps/_workspace/src/github.com/jbenet/go-random/.travis.yml
  Godeps/_workspace/src/github.com/jbenet/go-random/LICENSE
  Godeps/_workspace/src/github.com/jbenet/go-random/README.md
  Godeps/_workspace/src/github.com/jbenet/go-random/lib.go
  Godeps/_workspace/src/github.com/jbenet/go-random/random/.gitignore
  Godeps/_workspace/src/github.com/jbenet/go-random/random/random.go
  Godeps/_workspace/src/github.com/jbenet/go-random/random_test.go
  Godeps/_workspace/src/github.com/mitchellh/go-homedir/LICENSE
  Godeps/_workspace/src/github.com/mitchellh/go-homedir/README.md
  Godeps/_workspace/src/github.com/mitchellh/go-homedir/homedir.go
  Godeps/_workspace/src/github.com/mitchellh/go-homedir/homedir_test.go
  Godeps/_workspace/src/github.com/texttheater/golang-levenshtein/levenshtein/levenshtein.go
  Godeps/_workspace/src/github.com/texttheater/golang-levenshtein/levenshtein/levenshtein_test.go
  cmd/ipfs/Rules.mk
  cmd/ipfswatch/main.go
  coverage/Rules.mk
  mk/golang.mk
  package.json
  pin/internal/pb/doc.go
  repo/fsrepo/fsrepo.go
  repo/fsrepo/misc.go
  test/3nodetest/Makefile
  test/bench/bench_cli_ipfs_add/main.go
  test/bench/offline_add/main.go
  test/bin/Rules.mk
  test/bin/verify-go-fmt.sh
  test/integration/addcat_test.go
  test/sharness/lib/random-dep.go
Labels: in progress

#5451 api: fix outdated HTTPHeaders config documentation
  core/corehttp/commands.go
Labels: api, documentation, in progress

#5399 add --name new flag when ipfs adding from stdin
  core/commands/add.go
  core/coreunix/add.go
  test/sharness/t0040-add-and-cat.sh
Labels: RFM, commands

#4929 Refactor `ipfs p2p`
  core/commands/commands_test.go
  core/commands/p2p.go
  docs/experimental-features.md
  p2p/listener.go
  p2p/local.go
  p2p/p2p.go
  p2p/registry.go
  p2p/remote.go
  p2p/stream.go
  package.json
  test/sharness/t0180-p2p.sh
Labels: in progress

#5449 add rabin min error test
  test/sharness/t0040-add-and-cat.sh
Labels: in progress

#5481 coreapi name: Increase test swarm size
  core/coreapi/name_test.go
Labels: core-api, in progress, test failure

#5477 error when publishing ipns records without a running daemon
  core/commands/name/ipns.go
  core/commands/name/publish.go
  test/sharness/t0100-name.sh
  test/sharness/t0110-gateway.sh
  test/sharness/t0160-resolve.sh
Labels: in progress

#5466 make warnings on no bootstrap peers less noisy
  core/bootstrap.go
Labels: in progress

#5485 files cp: wrap flush error
  core/commands/files.go
Labels: RFM, commands

#5484 resolve: use unixfs ResolveOnce
  core/commands/resolve.go
  core/commands/root.go
  core/coreapi/interface/options/name.go
  core/coreapi/name.go
  core/coreapi/path.go
  core/coreapi/unixfs.go
  test/sharness/t0260-sharding.sh
Labels: core-api, in progress

#5035 update for the go-ipfs-cmds refactor
  cmd/ipfs/daemon.go
  cmd/ipfs/init.go
  cmd/ipfs/ipfs.go
  cmd/ipfs/main.go
  commands/legacy/command.go
  commands/legacy/legacy.go
  commands/legacy/legacy_test.go
  commands/legacy/request.go
  commands/legacy/response.go
  commands/request.go
  core/commands/add.go
  core/commands/bitswap.go
  core/commands/block.go
  core/commands/cat.go
  core/commands/cmdenv/env.go
  core/commands/commands.go
  core/commands/commands_test.go
  core/commands/files.go
  core/commands/filestore.go
  core/commands/get.go
  core/commands/get_test.go
  core/commands/helptext_test.go
  core/commands/keystore.go
  core/commands/name/ipns.go
  core/commands/name/ipnsps.go
  core/commands/name/name.go
  core/commands/name/publish.go
  core/commands/object/object.go
  core/commands/object/patch.go
  core/commands/pubsub.go
  core/commands/repo.go
  core/commands/resolve.go
  core/commands/root.go
  core/commands/shutdown.go
  core/commands/stat.go
  core/commands/urlstore.go
  core/corehttp/commands.go
  package.json
  test/sharness/README.md
  test/sharness/lib/test-lib.sh
  test/sharness/t0252-files-gc.sh
Labels: in progress

#5507 mk: embed CurrentCommit in the right place
  cmd/ipfs/Rules.mk
Labels: build, in progress

#5505 fix(unixfs): issue #5217 (Avoid use of `pb.Data`)
  core/commands/files.go
  core/commands/ls.go
  core/commands/unixfs/ls.go
Labels: RFM

#5496 fixed tests of raised fd limits
  cmd/ipfs/daemon.go
  cmd/ipfs/util/ulimit.go
  cmd/ipfs/util/ulimit_freebsd.go
  cmd/ipfs/util/ulimit_test.go
  cmd/ipfs/util/ulimit_unix.go
  mk/util.mk
Labels: waiting on author

#5525 fix(unixfs): issue #5055
  core/commands/ls.go
  core/commands/unixfs/ls.go
  fuse/readonly/readonly_unix.go
Labels: RFM

#5527 pprof: create HTTP endpoint for setting MutexProfileFraction
  cmd/ipfs/daemon.go
  core/corehttp/mutex_profile.go
  test/sharness/t0110-gateway.sh
Labels: in progress, needs review

#5512 Fix inability to pin two things at once
  pin/pin.go
Labels: in progress
