Repository ipfs/kubo, pull requests merged in 2018-07, with the labels that each got.

#5194 when running an external command, only construct a node if running in online mode
  core/commands/external.go
  test/sharness/t0063-external.sh
Labels: needs review

#5196 Ipfs 0.4.16 release candidate 2
  .gx/lastpubver
  CHANGELOG.md
  package.json
  repo/config/version.go
Labels: in progress

#5200 fix dht commands when pubsub routing is enabled
  core/commands/dht.go
  core/core.go
  package.json
  test/sharness/lib/iptb-lib.sh
  test/sharness/t0170-dht.sh
Labels: in progress, needs review

#5202 correctly handle multi-hop dnslink resolution
  core/corehttp/gateway_test.go
  core/corehttp/ipns_hostname.go
Labels: RFM

#5207 Ipfs v0.4.16-rc3
  CHANGELOG.md
  package.json
  repo/config/version.go
Labels: in progress

#5214 publish the gx 0.4.16-rc3 release
  .gx/lastpubver
Labels: in progress

#5179 Ipfs 0.4.16 release
  .gx/lastpubver
  CHANGELOG.md
  package.json
  repo/config/version.go
Labels: in progress, needs review

#4896 URL store
  core/builder.go
  core/commands/add.go
  core/commands/commands_test.go
  core/commands/filestore.go
  core/commands/root.go
  core/commands/urlstore.go
  docs/experimental-features.md
  filestore/filestore.go
  filestore/filestore_test.go
  filestore/fsrefstore.go
  importer/helpers/dagbuilder.go
  repo/config/experiments.go
  repo/fsrepo/fsrepo.go
  test/sharness/t0272-urlstore.sh
Labels: in progress, needs review

#5170 mfs: make `Root` value a `Directory`
  core/corerepo/gc.go
  core/coreunix/add.go
  fuse/ipns/ipns_unix.go
  mfs/mfs_test.go
  mfs/ops.go
  mfs/system.go
Labels: MFS, RFM, technical debt

#5139 feat: Allow specifing how object data is encoded
  core/commands/object/object.go
  test/sharness/t0051-object.sh
Labels: RFM

#5010 Efficient "repo stat" (DiskUsage) and "--size-only" flag
  core/commands/repo.go
  core/corerepo/stat.go
  repo/fsrepo/fsrepo.go
  test/sharness/t0080-repo.sh
Labels: RFM, in progress

#5045 cmd: fix `files ls` to report hash and size for files
  core/commands/files.go
  test/sharness/t0250-files-api.sh
Labels: RFM, files, technical debt

#5205 Refactor code
  cmd/ipfs/main.go
Labels: RFM

#5160 unixfs: add a directory interface
  mfs/dir.go
  unixfs/io/dirbuilder.go
  unixfs/io/directory.go
  unixfs/io/directory_test.go
Labels: RFM, UnixFS, technical debt

#4924 Add information about bloom filter to config.md
  docs/config.md
Labels: RFM, in progress

#5239 unixfs: fix `FSNode` accessor in `NewDirectoryFromNode`
  unixfs/io/directory.go
Labels: bug, build, in progress

#5118 importer: remove `UnixfsNode` from the balanced builder
  importer/balanced/builder.go
  importer/helpers/dagbuilder.go
  importer/helpers/helpers.go
Labels: RFM, UnixFS, files, in progress

#5162 always try to read ahead by at least 5 blocks in the PBDagReader
  unixfs/io/dagreader_test.go
  unixfs/io/pbdagreader.go
Labels: RFM

#4672 Improve paths in CoreApi
  core/coreapi/block.go
  core/coreapi/coreapi.go
  core/coreapi/dag.go
  core/coreapi/dag_test.go
  core/coreapi/interface/block.go
  core/coreapi/interface/coreapi.go
  core/coreapi/interface/dag.go
  core/coreapi/interface/object.go
  core/coreapi/interface/path.go
  core/coreapi/interface/pin.go
  core/coreapi/interface/unixfs.go
  core/coreapi/key.go
  core/coreapi/name.go
  core/coreapi/object.go
  core/coreapi/path.go
  core/coreapi/path_test.go
  core/coreapi/pin.go
  core/coreapi/pin_test.go
  core/coreapi/unixfs.go
  core/coreapi/unixfs_test.go
  core/corehttp/gateway_handler.go
  core/corehttp/gateway_test.go
  core/pathresolver.go
  path/path.go
  path/path_test.go
  path/resolver/resolver.go
Labels: RFM, core-api, discussion

#5253 fix truncating when already at the correct size
  mfs/mfs_test.go
  unixfs/mod/dagmodifier.go
Labels: RFM

#5245 add trickle-dag support to the urlstore
  core/commands/root.go
  core/commands/urlstore.go
  test/sharness/t0272-urlstore.sh
Labels: RFM

#5216 unixfs: fix `dagTruncate` to preserve node type
  mfs/mfs_test.go
  test/sharness/t0250-files-api.sh
  unixfs/mod/dagmodifier.go
  unixfs/mod/dagmodifier_test.go
  unixfs/unixfs.go
Labels: MFS, P1 - High, RFM, UnixFS, bug

#5237 unixfs: refactor `precalcNextBuf`
  unixfs/io/dagreader.go
  unixfs/io/pbdagreader.go
  unixfs/unixfs.go
Labels: RFM, UnixFS

#5218 commands/files: add error messages for `cp` paths
  core/commands/files.go
Labels: documentation, files, needs review

#5219 mfs: remove `sort` from `ListNames()`
  core/commands/files.go
  mfs/dir.go
  test/sharness/t0250-files-api.sh
Labels: MFS, RFM, files, technical debt

#5274 build tag to disable dynamic plugins
  plugin/loader/load_linux.go
Labels: in progress

#5261 fix check_go_path when it has spaces in it
  bin/check_go_path
  mk/golang.mk
Labels: RFM

#5262 mfs: seek to 0 before reading in `TestTruncateAndWrite`
  mfs/mfs_test.go
Labels: MFS, RFM, bug

#5276 test: testLargeWriteChunks: seek before reading
  unixfs/mod/dagmodifier_test.go
Labels: UnixFS, bug, needs review

#5271 Fix resolving links in sharded directories on gateway
  path/resolver/resolver.go
  test/sharness/t0260-sharding.sh
Labels: in progress

#5268 gx update deps
  blocks/blockstoreutil/remove.go
  blockservice/blockservice.go
  blockservice/blockservice_test.go
  blockservice/test/blocks_test.go
  cmd/ipfs/daemon.go
  core/builder.go
  core/commands/add.go
  core/commands/files.go
  core/commands/id.go
  core/commands/ls.go
  core/commands/pin.go
  core/commands/pubsub.go
  core/commands/repo.go
  core/commands/swarm.go
  core/core.go
  core/coreapi/pin.go
  core/corehttp/gateway.go
  core/corehttp/gateway_test.go
  core/corehttp/metrics.go
  core/corehttp/metrics_test.go
  core/coreunix/add.go
  core/coreunix/add_test.go
  core/coreunix/metadata_test.go
  core/mock/mock.go
  exchange/bitswap/bitswap.go
  exchange/bitswap/bitswap_test.go
  exchange/bitswap/decision/engine.go
  exchange/bitswap/decision/engine_test.go
  exchange/bitswap/get.go
  exchange/bitswap/testnet/peernet.go
  exchange/bitswap/testutils.go
  exchange/bitswap/wantmanager.go
  exchange/reprovide/providers.go
  exchange/reprovide/reprovide_test.go
  filestore/filestore.go
  filestore/filestore_test.go
  filestore/fsrefstore.go
  filestore/util.go
  merkledag/merkledag_test.go
  merkledag/test/utils.go
  merkledag/utils/utils.go
  mfs/mfs_test.go
  namesys/republisher/repub_test.go
  namesys/routing.go
  package.json
  pin/gc/gc.go
  pin/pin_test.go
  pin/set_test.go
  repo/config/bootstrap_peers.go
  repo/fsrepo/datastores.go
  repo/fsrepo/fsrepo.go
  test/integration/addcat_test.go
  test/integration/bench_cat_test.go
  test/integration/bitswap_wo_routing_test.go
  test/integration/three_legged_cat_test.go
  thirdparty/verifbs/verifbs.go
Labels: needs review

#5267 Release 0.4.17
  .gx/lastpubver
  CHANGELOG.md
  package.json
  repo/config/version.go
Labels: RFM

#5283 urlstore: Accept "200 OK" in addition to "206 Partial Content".
  filestore/fsrefstore.go
Labels: in progress

#5292 Ipfs v0.4.17
  .gx/lastpubver
  CHANGELOG.md
  package.json
  repo/config/version.go
Labels: RFM

#5294 Extract bitswap to go-bitswap
  Rules.mk
  blockservice/test/mock.go
  core/commands/bitswap.go
  core/core.go
  exchange/bitswap/README.md
  exchange/bitswap/bitswap.go
  exchange/bitswap/bitswap_test.go
  exchange/bitswap/decision/bench_test.go
  exchange/bitswap/decision/engine.go
  exchange/bitswap/decision/engine_test.go
  exchange/bitswap/decision/ledger.go
  exchange/bitswap/decision/peer_request_queue.go
  exchange/bitswap/decision/peer_request_queue_test.go
  exchange/bitswap/get.go
  exchange/bitswap/message/message.go
  exchange/bitswap/message/message_test.go
  exchange/bitswap/message/pb/Makefile
  exchange/bitswap/message/pb/Rules.mk
  exchange/bitswap/message/pb/message.pb.go
  exchange/bitswap/message/pb/message.proto
  exchange/bitswap/network/interface.go
  exchange/bitswap/network/ipfs_impl.go
  exchange/bitswap/notifications/notifications.go
  exchange/bitswap/notifications/notifications_test.go
  exchange/bitswap/session.go
  exchange/bitswap/session_test.go
  exchange/bitswap/stat.go
  exchange/bitswap/testnet/interface.go
  exchange/bitswap/testnet/network_test.go
  exchange/bitswap/testnet/peernet.go
  exchange/bitswap/testnet/virtual.go
  exchange/bitswap/testutils.go
  exchange/bitswap/wantlist/wantlist.go
  exchange/bitswap/wantlist/wantlist_test.go
  exchange/bitswap/wantmanager.go
  exchange/bitswap/workers.go
  package.json
Labels: in progress

#5296 Extract blockservice and verifcid
  blockservice/blockservice.go
  blockservice/blockservice_test.go
  blockservice/test/blocks_test.go
  blockservice/test/mock.go
  core/builder.go
  core/commands/add.go
  core/commands/files.go
  core/commands/ls.go
  core/commands/pin.go
  core/core.go
  core/coreapi/pin.go
  core/coreunix/add_test.go
  core/coreunix/metadata_test.go
  exchange/reprovide/reprovide.go
  merkledag/merkledag.go
  merkledag/merkledag_test.go
  merkledag/test/utils.go
  merkledag/utils/utils.go
  mfs/mfs_test.go
  package.json
  pin/gc/gc.go
  pin/pin_test.go
  pin/set_test.go
  thirdparty/verifbs/verifbs.go
  thirdparty/verifcid/validate.go
  thirdparty/verifcid/validate_test.go
Labels: in progress

#5306 Extract path and resolver
  core/builder.go
  core/commands/dag/dag.go
  core/commands/dht.go
  core/commands/files.go
  core/commands/get.go
  core/commands/ls.go
  core/commands/object/diff.go
  core/commands/object/object.go
  core/commands/object/patch.go
  core/commands/pin.go
  core/commands/publish.go
  core/commands/refs.go
  core/commands/resolve.go
  core/commands/tar.go
  core/commands/unixfs/ls.go
  core/core.go
  core/coreapi/interface/path.go
  core/coreapi/key.go
  core/coreapi/name.go
  core/coreapi/name_test.go
  core/coreapi/path.go
  core/corehttp/commands.go
  core/corehttp/gateway_handler.go
  core/corehttp/gateway_test.go
  core/corerepo/pinning.go
  core/coreunix/cat.go
  core/pathresolver.go
  core/pathresolver_test.go
  dagutils/utils.go
  dagutils/utils_test.go
  fuse/ipns/common.go
  fuse/ipns/ipns_unix.go
  fuse/readonly/readonly_unix.go
  mfs/mfs_test.go
  mfs/ops.go
  namesys/base.go
  namesys/cache.go
  namesys/dns.go
  namesys/interface.go
  namesys/ipns_resolver_validation_test.go
  namesys/namesys.go
  namesys/namesys_test.go
  namesys/proquint.go
  namesys/publisher.go
  namesys/republisher/repub.go
  namesys/republisher/repub_test.go
  namesys/resolve_test.go
  namesys/routing.go
  package.json
  path/path.go
  path/path_test.go
  path/resolver/resolver.go
  path/resolver/resolver_test.go
  tar/format.go
Labels: in progress

#5265 pin update fixes
  core/commands/pin.go
  test/sharness/t0085-pins.sh
Labels: RFM, in progress

#5315 wait for the nodes to fully stop
  package.json
  test/sharness/lib/iptb-lib.sh
  test/sharness/t0023-shutdown.sh
  test/sharness/t0125-twonode.sh
  test/sharness/t0130-multinode.sh
  test/sharness/t0175-reprovider.sh
  test/sharness/t0181-private-network.sh
  test/sharness/t0182-circuit-relay.sh
Labels: needs review

#5316 Extract unixfs and importers to go-unixfs
  assets/assets.go
  core/builder.go
  core/commands/add.go
  core/commands/files.go
  core/commands/get.go
  core/commands/ls.go
  core/commands/object/object.go
  core/commands/object/patch.go
  core/commands/pin.go
  core/commands/unixfs/ls.go
  core/commands/urlstore.go
  core/core.go
  core/coreapi/object.go
  core/coreapi/path.go
  core/coreapi/unixfs.go
  core/coreapi/unixfs_test.go
  core/corehttp/gateway_handler.go
  core/corerepo/pinning.go
  core/coreunix/add.go
  core/coreunix/cat.go
  core/coreunix/metadata.go
  core/coreunix/metadata_test.go
  fuse/ipns/common.go
  fuse/ipns/ipns_unix.go
  fuse/readonly/ipfs_test.go
  fuse/readonly/readonly_unix.go
  mfs/dir.go
  mfs/fd.go
  mfs/file.go
  mfs/mfs_test.go
  mfs/system.go
  namesys/namesys_test.go
  namesys/publisher.go
  package.json
  tar/format.go
  unixfs/archive/archive.go
  unixfs/archive/tar/writer.go
  unixfs/hamt/hamt.go
  unixfs/hamt/hamt_stress_test.go
  unixfs/hamt/hamt_test.go
  unixfs/importer/balanced/balanced_test.go
  unixfs/importer/balanced/builder.go
  unixfs/importer/helpers/dagbuilder.go
  unixfs/importer/helpers/helpers.go
  unixfs/importer/importer.go
  unixfs/importer/importer_test.go
  unixfs/importer/trickle/trickle_test.go
  unixfs/importer/trickle/trickledag.go
  unixfs/io/dagreader.go
  unixfs/io/dagreader_test.go
  unixfs/io/directory.go
  unixfs/io/directory_test.go
  unixfs/io/pbdagreader.go
  unixfs/io/resolve.go
  unixfs/mod/dagmodifier.go
  unixfs/mod/dagmodifier_test.go
  unixfs/test/utils.go
  unixfs/unixfs.go
  unixfs/unixfs_test.go
Labels: in progress
