Repository ipfs/kubo, pull requests merged in 2018-11, with the labels that each got.

#5702 prepare for RC2
  CHANGELOG.md
  version.go
Labels: in progress

#5712 cmds/env: add a config path helper
  core/commands/cmdenv/env.go
Labels: RFM

#5665 commands/files: use new cmds
  core/commands/files.go
Labels: in progress

#5666 commands/object: use new cmds
  core/commands/object/diff.go
  core/commands/object/object.go
  core/commands/object/patch.go
  core/commands/root.go
Labels: in progress

#5671 commands/dht: use new cmds lib
  core/commands/dht.go
  core/commands/root.go
Labels: in progress

#5672 commands/p2p: use new cmds lib
  core/commands/p2p.go
  core/commands/root.go
Labels: in progress

#5710 enhance(cmd/verify): add goroutine count to improve verify speed
  core/commands/repo.go
Labels: in progress

#5636 Update IPTB test
  package.json
  test/bin/Rules.mk
  test/dependencies/iptb/iptb.go
  test/sharness/lib/iptb-lib.sh
  test/sharness/t0030-mount.sh
  test/sharness/t0031-mount-publish.sh
  test/sharness/t0041-ping.sh
  test/sharness/t0101-iptb-name.sh
  test/sharness/t0121-bootstrap-iptb.sh
  test/sharness/t0125-twonode.sh
  test/sharness/t0130-multinode.sh
  test/sharness/t0131-multinode-client-routing.sh
  test/sharness/t0140-swarm.sh
  test/sharness/t0170-dht.sh
  test/sharness/t0175-reprovider.sh
  test/sharness/t0180-p2p.sh
  test/sharness/t0180-pubsub-gossipsub.sh
  test/sharness/t0180-pubsub.sh
  test/sharness/t0181-private-network.sh
  test/sharness/t0182-circuit-relay.sh
  test/sharness/t0183-namesys-pubsub.sh
  test/sharness/t0190-quic-ping.sh
  test/sharness/t0240-republisher.sh
  test/sharness/t0276-cidv0v1.sh
Labels: in progress

#5695 Move persistent datastores to plugins
  cmd/ipfs/main.go
  plugin/loader/load.go
  plugin/loader/preload.go
  plugin/loader/preload_list
  plugin/plugins/Rules.mk
  plugin/plugins/badgerds/badgerds.go
  plugin/plugins/flatfs/flatfs.go
  plugin/plugins/levelds/levelds.go
  repo/fsrepo/config_test.go
  repo/fsrepo/datastores.go
Labels: in progress

#5718 fix the maketarball script
  bin/maketarball.sh
Labels: in progress

#5741 gx: fix broken import
  repo/fsrepo/config_test.go
Labels: in progress

#5676 commands/bitswap: use new cmds lib
  core/commands/bitswap.go
Labels: in progress

#5673 commands/filestore: use new cmds lib
  core/commands/filestore.go
Labels: in progress

#5659 refactor(cmds): use new cmds
  core/commands/active.go
  core/commands/config.go
  core/commands/diag.go
  core/commands/log.go
  core/commands/mount_nofuse.go
  core/commands/mount_unix.go
  core/commands/mount_windows.go
  core/commands/root.go
  core/commands/sysdiag.go
Labels: in progress

#5747 unexport GOFLAGS
  mk/golang.mk
Labels: in progress

#5743 fix(cmd/add): progressbar output error when input is read from stdin
  core/commands/add.go
Labels: in progress

#5674 commands/pin: use new cmds lib
  core/commands/pin.go
  core/commands/root.go
Labels: in progress

#5730 cmds/update: use new cmds lib
  core/commands/external.go
  core/commands/root.go
Labels: in progress

#5770 ISSUE_TEMPLATE: move the support question comment to the very top
  ISSUE_TEMPLATE.md
Labels: in progress

#5782 Switch to using request.Context()
  core/corehttp/gateway_handler.go
Labels: in progress

#5611 Add --stream option to `ls` command
  core/commands/ls.go
  core/commands/root.go
  test/sharness/t0045-ls.sh
Labels: blocked by steb, in progress

#5798 gx: update go-ipfs-config
  cmd/ipfs/init.go
  cmd/ipfs/main.go
  cmd/ipfswatch/main.go
  commands/request.go
  core/bootstrap.go
  core/bootstrap_test.go
  core/builder.go
  core/commands/bootstrap.go
  core/commands/cmdenv/env.go
  core/commands/config.go
  core/commands/mount_unix.go
  core/commands/repo.go
  core/commands/swarm.go
  core/core.go
  core/core_test.go
  core/coreapi/unixfs_test.go
  core/corehttp/commands.go
  core/corehttp/gateway_test.go
  core/coreunix/add_test.go
  core/mock/mock.go
  package.json
  repo/fsrepo/config_test.go
  repo/fsrepo/fsrepo.go
  repo/fsrepo/fsrepo_test.go
  repo/fsrepo/misc.go
  repo/mock.go
  repo/repo.go
  test/bench/bench_cli_ipfs_add/main.go
  test/bench/offline_add/main.go
  test/dependencies/iptb/iptb.go
Labels: in progress

#5625 badger: add truncate flag
  docs/datastores.md
  plugin/plugins/badgerds/badgerds.go
Labels: badger

#5786 cmds: rm old lib
  commands/command.go
  commands/context.go
  commands/legacy/command.go
  commands/legacy/legacy.go
  commands/legacy/legacy_test.go
  commands/legacy/request.go
  commands/legacy/response.go
  commands/reqlog.go
  commands/response.go
  core/commands/cmdenv/env.go
Labels: in progress

#5809 coreapi/pin: Use CID's directly in maps instead of converting to string
  core/coreapi/pin.go
Labels: in progress

#5526 [http_proxy_over_p2p]
  cmd/ipfs/daemon.go
  core/corehttp/proxy.go
  core/corehttp/proxy_test.go
  docs/experimental-features.md
  package.json
  test/sharness/t0184-http-proxy-over-p2p.sh
Labels: in progress

#5771 p2p: report-peer-id option for listen
  core/commands/p2p.go
  p2p/remote.go
  test/sharness/t0180-p2p.sh
Labels: in progress, needs review
