Repository ipfs/kubo, pull requests merged in 2019-03, with the labels that each got.

#6026 Release 0.4.19
  .gx/lastpubver
  CHANGELOG.md
  package.json
  version.go
Labels: in progress

#6040 Revert "Really run as non-root user in docker container"
  Dockerfile
  Dockerfile.fast
Labels: in progress

#6034 commands(dht): return final error
  core/commands/dht.go
  core/core.go
  package.json
  test/sharness/t0170-dht.sh
Labels: in progress, needs review

#6013 Improve CLI help pages
  core/commands/log.go
  core/commands/root.go
Labels: RFM, in progress

#5820 feat/cmds: hide peers info default in bitswap stat
  core/commands/bitswap.go
Labels: in progress

#5429 ci: test on 32bit os
  ci/Jenkinsfile
  core/corehttp/gateway_test.go
  mk/golang.mk
  test/bin/Rules.mk
Labels: in progress

#6050 cleanup daemon online logic
  cmd/ipfs/daemon.go
  cmd/ipfs/init.go
  cmd/ipfs/main.go
  cmd/ipfswatch/main.go
  commands/context.go
  core/builder.go
  core/commands/bitswap.go
  core/commands/dht.go
  core/commands/external.go
  core/commands/id.go
  core/commands/mount_unix.go
  core/commands/p2p.go
  core/commands/ping.go
  core/commands/shutdown.go
  core/commands/stat.go
  core/commands/sysdiag.go
  core/core.go
  core/coreapi/coreapi.go
  core/corehttp/gateway_handler.go
  core/mock/mock.go
  fuse/node/mount_unix.go
Labels: in progress

#6049 yamux: increase yamux window size to 8MiB.
  core/core.go
Labels: in progress

#6057 go: require Golang 1.11.4
  mk/golang.mk
Labels: in progress

#6059 mk: fix make install by not setting GOBIN
  coverage/Rules.mk
  coverage/tools.go
  go.mod
  mk/golang.mk
  test/bin/Rules.mk
  test/dependencies/dependencies.go
Labels: in progress

#6060 mk: change git-hash command to include information about modifications
  mk/git.mk
Labels: in progress

#6063 mk: remove install_unsupported, leave a note
  Rules.mk
Labels: in progress

#6051 fix ls command to use the new coreinterface types
  core/commands/ls.go
  core/coreapi/unixfs.go
  go.mod
  go.sum
  package.json
Labels: in progress

#6078 mk: fix maketarball to work with gomod
  bin/maketarball.sh
  mk/golang.mk
Labels: in progress

#6088 deps: update go-bitswap
  go.mod
  go.sum
  package.json
Labels: in progress

#6090 gx: update go-ipfs-cmds
  go.mod
  go.sum
  package.json
Labels: in progress

#6085 make in-memory datastore thread-safe
  repo/fsrepo/datastores.go
  repo/repo.go
Labels: in progress

#5535 fix(swarm): add dnsaddr support in swarm connect
  core/commands/swarm.go
Labels: in progress

#6087 resolve: fix recursion
  core/commands/dns.go
  core/commands/name/ipns.go
  core/commands/resolve.go
  test/sharness/t0160-resolve.sh
Labels: in progress

#6094 gomod: update go-mfs
  core/commands/files.go
  go.mod
  go.sum
  package.json
Labels: in progress

#6102 Return CID from 'ipfs files flush'
  core/commands/files.go
  go.mod
  go.sum
  package.json
Labels: in progress

#6100 gomod: Update Dockerfile, remove Dockerfile.fast
  Dockerfile
  Dockerfile.fast
  test/3nodetest/Makefile
  test/sharness/t0300-docker-image.sh
  test/sharness/t0301-docker-migrate.sh
Labels: in progress

#6068 Provide root node immediately on add and pin add
  core/builder.go
  core/core.go
  core/coreapi/coreapi.go
  core/coreapi/pin.go
  core/coreapi/provider.go
  core/coreapi/unixfs.go
  go.mod
  provider/offline.go
  provider/provider.go
  provider/provider_test.go
  provider/queue.go
  provider/queue_test.go
Labels: in progress

#6109 update go-libp2p-kad-dht
  go.mod
  go.sum
  package.json
Labels: in progress

#6112 gc: fix a potential deadlock
  pin/gc/gc.go
Labels: in progress

#6119 deps: switch back to jbenet go-is-domain
  core/corehttp/ipns_hostname.go
  go.mod
  go.sum
  package.json
Labels: in progress

#6120 dep: update files, cmds, interfaces
  go.mod
  go.sum
  package.json
Labels: in progress

#6019 coreapi unixfs: change Wrap logic to make more sense
  core/commands/add.go
  core/coreapi/unixfs.go
  core/corehttp/gateway_test.go
  core/coreunix/add.go
  go.mod
  go.sum
  package.json
  test/sharness/t0080-repo.sh
  test/sharness/t0175-reprovider.sh
Labels: in progress

#6123 coreapi: remove Unixfs.Wrap
  core/coreapi/unixfs.go
  core/coreunix/add.go
  go.mod
  go.sum
Labels: in progress

#6125 Query for provider head/tail
  go.mod
  go.sum
  provider/queue.go
  provider/queue_test.go
Labels: in progress

#6147 interrupt: fix send on closed
  cmd/ipfs/util/signal.go
Labels: in progress

#6140 chore: fix a bunch of issues caught by golangci-lint
  cmd/ipfs/daemon.go
  cmd/ipfs/main.go
  cmd/ipfswatch/main.go
  cmd/seccat/seccat.go
  commands/reqlog.go
  core/builder.go
  core/commands/add.go
  core/commands/cid.go
  core/commands/commands.go
  core/commands/config.go
  core/commands/files.go
  core/commands/get.go
  core/commands/p2p.go
  core/commands/repo.go
  core/commands/swarm.go
  core/core.go
  core/coreapi/pubsub.go
  core/coreapi/swarm.go
  core/corehttp/gateway_test.go
  core/corehttp/mutex_profile.go
  core/corehttp/option_test.go
  core/corerepo/gc.go
  core/coreunix/add_test.go
  core/coreunix/metadata_test.go
  dagutils/diff.go
  dagutils/utils.go
  exchange/reprovide/reprovide_test.go
  fuse/ipns/ipns_test.go
  fuse/mount/fuse.go
  fuse/node/mount_unix.go
  fuse/readonly/ipfs_test.go
  keystore/keystore_test.go
  namesys/namesys.go
  namesys/namesys_test.go
  namesys/republisher/repub_test.go
  namesys/routing.go
  p2p/remote.go
  p2p/stream.go
  pin/pin_test.go
  plugin/loader/loader.go
  provider/queue.go
  provider/queue_test.go
  test/bench/bench_cli_ipfs_add/main.go
  test/bench/offline_add/main.go
  test/dependencies/ma-pipe-unidir/main.go
  test/integration/addcat_test.go
  test/integration/bench_cat_test.go
  test/integration/bitswap_wo_routing_test.go
  test/integration/three_legged_cat_test.go
Labels: in progress

#6157 chore: remove waffle
  README.md
Labels: in progress

#6156 fix add error handling
  core/coreapi/unixfs.go
  core/coreunix/add.go
  test/sharness/t0270-filestore.sh
  test/sharness/t0272-urlstore.sh
Labels: in progress
