Repository ipfs/kubo, pull requests merged in 2019-01, with the labels that each got.

#5856 testing: slow down republisher sharness test
  test/sharness/t0240-republisher.sh
Labels: in progress, needs review

#5885 Fix name resolve --offline
  core/coreapi/coreapi.go
  test/sharness/t0100-name.sh
Labels: in progress

#5854 coreapi/unixfs: Use path instead of raw hash in AddEvent
  core/commands/add.go
  core/commands/tar.go
  core/coreapi/interface/path.go
  core/coreapi/interface/unixfs.go
  core/coreapi/unixfs_test.go
  core/coreunix/add.go
  core/coreunix/add_test.go
Labels: in progress

#5889 Move checkHelptextRecursive forward a bit
  core/commands/helptext_test.go
  core/commands/urlstore.go
Labels: in progress

#5865 Move coreapi tests to the interface
  core/coreapi/dag.go
  core/coreapi/dht_test.go
  core/coreapi/interface/tests/api.go
  core/coreapi/interface/tests/block.go
  core/coreapi/interface/tests/dag.go
  core/coreapi/interface/tests/dht.go
  core/coreapi/interface/tests/key.go
  core/coreapi/interface/tests/name.go
  core/coreapi/interface/tests/object.go
  core/coreapi/interface/tests/path.go
  core/coreapi/interface/tests/pin.go
  core/coreapi/interface/tests/pubsub.go
  core/coreapi/interface/tests/unixfs.go
  core/coreapi/test/api_test.go
Labels: core-api, in progress, needs review, testing

#5830 Show hash on gateway
  assets/assets.go
  assets/bindata.go
  core/corehttp/gateway_handler.go
  core/corehttp/gateway_indexPage.go
  core/corehttp/gateway_test.go
  package.json
Labels: in progress

#5649 Local Gateway option
  cmd/ipfs/daemon.go
  cmd/ipfs/init.go
  cmd/ipfs/main.go
  cmd/ipfswatch/main.go
  commands/context.go
  core/bootstrap.go
  core/bootstrap_test.go
  core/builder.go
  core/commands/bootstrap.go
  core/commands/cmdenv/env.go
  core/commands/config.go
  core/commands/mount_unix.go
  core/commands/repo.go
  core/commands/swarm.go
  core/core.go
  core/core_test.go
  core/coreapi/coreapi.go
  core/coreapi/interface/options/global.go
  core/coreapi/interface/path.go
  core/coreapi/interface/tests/path.go
  core/coreapi/test/api_test.go
  core/coreapi/unixfile.go
  core/corehttp/commands.go
  core/corehttp/gateway.go
  core/corehttp/gateway_handler.go
  core/corehttp/gateway_test.go
  core/coreunix/add_test.go
  core/mock/mock.go
  package.json
  repo/fsrepo/config_test.go
  repo/fsrepo/fsrepo.go
  repo/fsrepo/fsrepo_test.go
  repo/fsrepo/misc.go
  repo/mock.go
  repo/repo.go
  test/bench/bench_cli_ipfs_add/main.go
  test/bench/offline_add/main.go
  test/dependencies/iptb/iptb.go
  test/sharness/t0110-gateway.sh
Labels: gateway, in progress

#5900 CoreAPI: Don't panic when testing incomplete implementions
  core/coreapi/interface/tests/api.go
  core/coreapi/interface/tests/block.go
  core/coreapi/interface/tests/dag.go
  core/coreapi/interface/tests/dht.go
  core/coreapi/interface/tests/key.go
  core/coreapi/interface/tests/name.go
  core/coreapi/interface/tests/object.go
  core/coreapi/interface/tests/path.go
  core/coreapi/interface/tests/pin.go
  core/coreapi/interface/tests/pubsub.go
  core/coreapi/interface/tests/unixfs.go
Labels: in progress, needs review

#5899 feat: update to Web UI v2.3.2
  core/corehttp/webui.go
Labels: RFM

#5919 [CORS] Bubble go-ipfs-cmds 2.0.10 - Updates CORS library
  cmd/ipfs/daemon.go
  cmd/ipfs/init.go
  cmd/ipfs/ipfs.go
  cmd/ipfs/main.go
  commands/context.go
  core/commands/active.go
  core/commands/add.go
  core/commands/bitswap.go
  core/commands/block.go
  core/commands/bootstrap.go
  core/commands/cat.go
  core/commands/cid.go
  core/commands/cmdenv/env.go
  core/commands/commands.go
  core/commands/commands_test.go
  core/commands/config.go
  core/commands/dag/dag.go
  core/commands/dht.go
  core/commands/diag.go
  core/commands/dns.go
  core/commands/external.go
  core/commands/files.go
  core/commands/filestore.go
  core/commands/get.go
  core/commands/get_test.go
  core/commands/helptext_test.go
  core/commands/id.go
  core/commands/keystore.go
  core/commands/log.go
  core/commands/ls.go
  core/commands/mount_nofuse.go
  core/commands/mount_unix.go
  core/commands/mount_windows.go
  core/commands/name/ipns.go
  core/commands/name/ipnsps.go
  core/commands/name/name.go
  core/commands/name/publish.go
  core/commands/object/diff.go
  core/commands/object/object.go
  core/commands/object/patch.go
  core/commands/p2p.go
  core/commands/pin.go
  core/commands/ping.go
  core/commands/pubsub.go
  core/commands/refs.go
  core/commands/repo.go
  core/commands/resolve.go
  core/commands/root.go
  core/commands/shutdown.go
  core/commands/stat.go
  core/commands/swarm.go
  core/commands/sysdiag.go
  core/commands/tar.go
  core/commands/unixfs/ls.go
  core/commands/unixfs/unixfs.go
  core/commands/urlstore.go
  core/commands/version.go
  core/corehttp/commands.go
  package.json
  test/sharness/t0062-daemon-api.sh
Labels: in progress

#5906 ls: Report real file size
  core/commands/ls.go
  test/sharness/t0045-ls.sh
  test/sharness/t0051-object.sh
  test/sharness/t0260-sharding.sh
Labels: in progress, needs review

#5926 coreapi: Adjust some tests for go-ipfs-http-api
  core/coreapi/interface/tests/block.go
  core/coreapi/interface/tests/dht.go
  core/coreapi/interface/tests/key.go
  core/coreapi/interface/tests/object.go
Labels: core-api, in progress

#5789 Add global option to specify the multibase encoding (server side)
  core/commands/add.go
  core/commands/bitswap.go
  core/commands/cid.go
  core/commands/cmdenv/cidbase.go
  core/commands/cmdenv/cidbase_test.go
  core/commands/dag/dag.go
  core/commands/files.go
  core/commands/filestore.go
  core/commands/ls.go
  core/commands/object/object.go
  core/commands/pin.go
  core/commands/refs.go
  core/commands/resolve.go
  core/commands/root.go
  core/commands/tar.go
  core/commands/urlstore.go
  core/coreapi/dht.go
  core/coreapi/unixfs.go
  exchange/reprovide/providers.go
  filestore/util.go
  package.json
  test/sharness/t0040-add-and-cat.sh
  test/sharness/t0045-ls.sh
  test/sharness/t0051-object-data/mixed.json
  test/sharness/t0051-object.sh
  test/sharness/t0053-dag.sh
  test/sharness/t0085-pins.sh
  test/sharness/t0095-refs.sh
  test/sharness/t0160-resolve.sh
  test/sharness/t0210-tar.sh
  test/sharness/t0250-files-api.sh
  test/sharness/t0271-filestore-utils.sh
  test/sharness/t0272-urlstore.sh
Labels: cidv1b32, in progress, needs review

#5922 coreapi: replace coreiface.DagAPI with ipld.DAGService
  core/coreapi/coreapi.go
  core/coreapi/dag.go
  core/coreapi/interface/coreapi.go
  core/coreapi/interface/dag.go
  core/coreapi/interface/options/dag.go
  core/coreapi/interface/tests/dag.go
  core/coreapi/interface/tests/path.go
  core/coreapi/interface/tests/pin.go
  core/coreapi/interface/tests/unixfs.go
Labels: core-api, discussion, in progress

#5920 Fixed and cleaned up TestIpfsStressRead
  fuse/readonly/ipfs_test.go
Labels: in progress

#5935 coreapi: few more error check fixes
  core/coreapi/interface/tests/dag.go
  core/coreapi/interface/tests/path.go
  core/coreapi/interface/tests/unixfs.go
Labels: core-api, in progress, testing

#5864 docs/code-flow : Add code flow documentation for add cmd.
  README.md
  docs/add-code-flow.md
Labels: RFM, documentation

#5936 mfs: make sure to flush after mv and chcid
  core/commands/files.go
Labels: in progress

#5939 Port dag commansds to CoreAPI
  core/commands/dag/dag.go
  core/coreapi/coreapi.go
  core/coreapi/dag.go
  core/coreapi/interface/coreapi.go
  core/coreapi/interface/dag.go
Labels: core-api, in progress

#5940 commands: fix verbose flag
  core/commands/active.go
  core/commands/dht.go
Labels: in progress

#5938 Drop some coreunix code
  assets/assets.go
  cmd/ipfswatch/main.go
  core/corehttp/gateway_test.go
  core/coreunix/add.go
  core/coreunix/add_test.go
  test/integration/addcat_test.go
  test/integration/bench_cat_test.go
  test/integration/three_legged_cat_test.go
Labels: core-api, in progress

#5651 clarification the document of --resolve flag in name.publish
  core/commands/name/publish.go
Labels: in progress

#5950 Only perform DNSLink lookups on fully qualified domain names (FQDN)
  namesys/dns.go
  namesys/dns_test.go
Labels: RFM

#5843 cmds/pin: use coreapi/pin
  core/commands/pin.go
  core/coreapi/interface/options/pin.go
  core/coreapi/interface/pin.go
  core/coreapi/pin.go
  core/corerepo/pinning.go
  test/sharness/t0080-repo.sh
Labels: core-api, in progress, needs rebase

#5934 coreapi: add some seeker tests
  core/coreapi/interface/tests/unixfs.go
Labels: core-api, in progress, testing

#5955 plugin: add a daemon plugin with access to the CoreAPI
  cmd/ipfs/daemon.go
  cmd/ipfs/main.go
  docs/plugins.md
  plugin/daemon.go
  plugin/loader/loader.go
  repo/fsrepo/config_test.go
Labels: in progress
