Repository ipfs/kubo, pull requests merged in 2019-02, with the labels that each got.

#5960 docs: duplicate default helptext in `name publish`
  core/commands/name/publish.go
Labels: in progress

#5962 Port `ipfs ls` to CoreAPI
  core/commands/ls.go
  core/coreapi/interface/options/unixfs.go
  core/coreapi/interface/tests/unixfs.go
  core/coreapi/interface/unixfs.go
  core/coreapi/unixfs.go
Labels: core-api, in progress

#5969 block put --pin
  core/commands/block.go
  core/coreapi/block.go
  core/coreapi/interface/options/block.go
  core/coreapi/interface/tests/block.go
Labels: RFM, in progress

#5971 coreapi: fix seek test on http impl
  core/coreapi/interface/tests/unixfs.go
Labels: core-api, in progress

#5976 coreapi: cleanup non-gx references
  core/commands/dns.go
  core/commands/name/ipns.go
  core/commands/resolve.go
  core/coreapi/interface/options/name.go
  core/coreapi/interface/options/namesys/opts.go
  core/coreapi/interface/tests/dag.go
  core/coreapi/interface/tests/path.go
  core/coreapi/interface/tests/pin.go
  core/corehttp/gateway_test.go
  core/corehttp/ipns_hostname.go
  namesys/base.go
  namesys/dns.go
  namesys/dns_test.go
  namesys/interface.go
  namesys/ipns_resolver_validation_test.go
  namesys/namesys.go
  namesys/namesys_test.go
  namesys/proquint.go
  namesys/routing.go
Labels: core-api, in progress

#5964 fix(cmd/mv): dst filename error
  test/sharness/t0250-files-api.sh
Labels: in progress

#5999 docs: document Gateway.NoFetch
  docs/config.md
Labels: in progress

#5704 fix: return the shortest, completely resolved path in the resolve command
  core/commands/resolve.go
  test/sharness/t0160-resolve.sh
Labels: in progress

#6001 CHANGELOG: add 0.4.19
  CHANGELOG.md
Labels: in progress

#6015 release 0.4.19-rc1
  .gx/lastpubver
  package.json
  version.go
Labels: in progress

#6023 gx: update go-ipfs-cmds
  cmd/ipfs/daemon.go
  cmd/ipfs/init.go
  cmd/ipfs/ipfs.go
  cmd/ipfs/main.go
  commands/context.go
  core/commands/active.go
  core/commands/add.go
  core/commands/bitswap.go
  core/commands/block.go
  core/commands/bootstrap.go
  core/commands/cat.go
  core/commands/cid.go
  core/commands/cmdenv/cidbase.go
  core/commands/cmdenv/env.go
  core/commands/commands.go
  core/commands/commands_test.go
  core/commands/config.go
  core/commands/dag/dag.go
  core/commands/dht.go
  core/commands/diag.go
  core/commands/dns.go
  core/commands/external.go
  core/commands/files.go
  core/commands/filestore.go
  core/commands/get.go
  core/commands/get_test.go
  core/commands/helptext_test.go
  core/commands/id.go
  core/commands/keystore.go
  core/commands/log.go
  core/commands/ls.go
  core/commands/mount_nofuse.go
  core/commands/mount_unix.go
  core/commands/mount_windows.go
  core/commands/name/ipns.go
  core/commands/name/ipnsps.go
  core/commands/name/name.go
  core/commands/name/publish.go
  core/commands/object/diff.go
  core/commands/object/object.go
  core/commands/object/patch.go
  core/commands/p2p.go
  core/commands/pin.go
  core/commands/ping.go
  core/commands/pubsub.go
  core/commands/refs.go
  core/commands/repo.go
  core/commands/resolve.go
  core/commands/root.go
  core/commands/shutdown.go
  core/commands/stat.go
  core/commands/swarm.go
  core/commands/sysdiag.go
  core/commands/tar.go
  core/commands/unixfs/ls.go
  core/commands/unixfs/unixfs.go
  core/commands/urlstore.go
  core/commands/version.go
  core/corehttp/commands.go
  package.json
Labels: in progress

#6025 Revert "chore: update to Web UI 2.4.0"
  core/corehttp/webui.go
Labels: in progress

#6031 Release 0.4.19-rc2
  .gx/lastpubver
  CHANGELOG.md
  package.json
  version.go
Labels: in progress
