Repository ipfs/kubo, pull requests merged in 2019-05, with the labels that each got.

#6285 dep: update go-ipfs-config
  go.mod
  go.sum
  test/sharness/t0020-init.sh
  test/sharness/t0021-config.sh
Labels: in progress

#6288 Test and fix GC/pin bug
  core/coreunix/add.go
  core/coreunix/add_test.go
Labels: in progress

#6289 core: fix autonat construction
  core/node/groups.go
  core/node/helpers.go
Labels: in progress

#6275 commands(pin update): return resolved CIDs instead of paths
  core/commands/pin.go
Labels: in progress

#6301 License update to dual MIT and Apache 2
  COPYRIGHT
  LICENSE-APACHE
  LICENSE-MIT
Labels: in progress

#5560 fix(Dockerfile): Allow ipfs mount in Docker container
  Dockerfile
Labels: in progress

#6222 test(coreapi): use a thread-safe datastore everywhere
  core/coreapi/test/api_test.go
Labels: in progress

#6312 ping: fix a bunch of issues
  core/commands/ping.go
  go.mod
  go.sum
  test/sharness/t0041-ping.sh
Labels: in progress

#6316 dep: update goprocess
  go.mod
  go.sum
Labels: in progress

#6308 Update to latest go-mfs
  go.mod
  go.sum
Labels: in progress

#6311 pin: don't walk all pinned blocks when removing a non-existent pin
  pin/pin.go
Labels: in progress

#6266 raise default fd limit to 8192
  cmd/ipfs/util/ulimit.go
Labels: in progress

#6300 switch to base32 by default for CIDv1
  docs/gateway.md
  go.mod
  go.sum
  test/sharness/t0040-add-and-cat.sh
  test/sharness/t0043-add-w.sh
  test/sharness/t0044-add-symlink.sh
  test/sharness/t0045-ls.sh
  test/sharness/t0046-id-hash.sh
  test/sharness/t0050-block.sh
  test/sharness/t0051-object.sh
  test/sharness/t0052-object-diff.sh
  test/sharness/t0053-dag.sh
  test/sharness/t0087-repo-robust-gc.sh
  test/sharness/t0250-files-api.sh
  test/sharness/t0260-sharding.sh
  test/sharness/t0271-filestore-utils.sh
  test/sharness/t0272-urlstore.sh
  test/sharness/t0275-cid-security.sh
  test/sharness/t0276-cidv0v1.sh
  test/sharness/t0280-plugin-git.sh
Labels: in progress

#6319 fix setting ulimit
  cmd/ipfs/util/ulimit.go
  cmd/ipfs/util/ulimit_test.go
Labels: bug

#6277 work towards fixing dht commands
  core/commands/dht.go
  test/sharness/t0170-dht.sh
Labels: in progress

#6352 core: Use correct default for connmgr lowWater
  core/node/groups.go
Labels: bug

#6292 Introduce first strategic provider: do nothing
  core/builder.go
  core/commands/bitswap.go
  core/core.go
  core/coreapi/coreapi.go
  core/node/core.go
  core/node/groups.go
  core/node/provider.go
  docs/experimental-features.md
  go.mod
  go.sum
  provider/offline.go
  provider/provider.go
  provider/queue/queue.go
  provider/queue/queue_test.go
  provider/simple/provider.go
  provider/simple/provider_test.go
  provider/simple/reprovide.go
  provider/simple/reprovide_test.go
  provider/system.go
  reprovide/providers.go
  reprovide/reprovide.go
  test/sharness/lib/test-lib.sh
  test/sharness/t0175-provider.sh
  test/sharness/t0175-reprovider.sh
  test/sharness/t0175-strategic-provider.sh
Labels: WIP, in progress
