Repository ipfs/kubo, pull requests merged in 2020-07, with the labels that each got.

#7441 feat: support ED25519 at subdomain gw with TLS
  core/corehttp/hostname.go
  core/corehttp/hostname_test.go
  test/sharness/t0114-gateway-subdomains.sh
  test/sharness/t0184-http-proxy-over-p2p.sh
Labels: topic/cidv1b32, topic/ed25519, topic/gateway

#7251 Choose Key type at initialization
  cmd/ipfs/daemon.go
  cmd/ipfs/init.go
  go.mod
  go.sum
  test/sharness/lib/test-lib.sh
  test/sharness/t0020-init.sh
  test/sharness/t0114-gateway-subdomains.sh
Labels: status/blocked

#7477 fix: override GOFLAGS
  mk/golang.mk
Labels: need/review
