Repository ipfs/kubo, pull requests merged in 2021-05, with the labels that each got.

#8097 chore: update webui to 2.12.2
  core/corehttp/webui.go
Labels: topic/webui

#8111 feat(gw): expose /api/v0/dag/export on gateway port
  core/commands/commands_test.go
  core/commands/root.go
  test/sharness/t0110-gateway.sh
Labels: topic/gateway

#8071 feat: support DNSLink on non-ICANN DNS names
  core/corehttp/hostname.go
  core/corehttp/hostname_test.go
  go.mod
  go.sum
Labels: status/accepted, topic/dns, topic/gateway

#8031 config.md: fix typos/improve wording
  docs/config.md
Labels: need/author-input

#8056 refactor(pinmfs): log error if pre-existing pin failed
  cmd/ipfs/pinmfs.go
  cmd/ipfs/pinmfs_test.go
Labels: P3, kind/enhancement

#8151 fix: webui-2.12.3
  core/corehttp/webui.go
Labels: P0
