Repository ipfs/kubo, pull requests merged in 2021-01, with the labels that each got.

#7847 feat(gw): DNSLink names on https:// subdomains
  core/corehttp/hostname.go
  core/corehttp/hostname_test.go
  docs/config.md
  test/sharness/t0114-gateway-subdomains.sh
Labels: P0, topic/gateway

#7802 feat(gw): URI router for Web API navigator.registerProtocolHandler
  core/corehttp/gateway_handler.go
  core/corehttp/gateway_test.go
  test/sharness/t0114-gateway-subdomains.sh
Labels: need/review, topic/gateway

#7807 fix: improved error message on broken CIDv0
  go.mod
  go.sum
Labels: need/review, topic/cidv1b32

#7829 fix: remote services ls always return a list
  core/commands/pin/remotepin.go
  test/sharness/t0700-remotepin.sh
Labels: status/accepted

#7823 docs: improved --help for pin remote commands
  core/commands/pin/remotepin.go
Labels: need/review

#7828 fix: normalize remote service endpoint
  core/commands/pin/remotepin.go
  core/commands/pin/remotepin_test.go
  test/sharness/t0700-remotepin.sh
Labels: need/review
