Repository ipfs/kubo, pull requests merged in 2024-09, with the labels that each got.

#10502 fix: switch back to go1.22
  .github/workflows/codeql-analysis.yml
  .github/workflows/docker-build.yml
  .github/workflows/gateway-conformance.yml
  .github/workflows/gobuild.yml
  .github/workflows/golang-analysis.yml
  .github/workflows/golint.yml
  .github/workflows/gotest.yml
  .github/workflows/interop.yml
  .github/workflows/sharness.yml
  Dockerfile
  docs/examples/kubo-as-a-library/go.mod
  go.mod
Labels: skip/changelog

#10505 docs: replace outdated package paths described in rpc README
  client/rpc/README.md
Labels: skip/changelog

#10507 chore: boxo v0.23.0 and go-libp2p v0.36.3
  README.md
  docs/changelogs/v0.30.md
  docs/examples/kubo-as-a-library/go.mod
  docs/examples/kubo-as-a-library/go.sum
  go.mod
  go.sum
  test/dependencies/go.mod
  test/dependencies/go.sum
  test/sharness/lib/install-sharness.sh
Labels: skip/changelog

#10496 docs: update RELEASE_CHECKLIST.md
  docs/EARLY_TESTERS.md
  docs/RELEASE_CHECKLIST.md
  docs/RELEASE_ISSUE_TEMPLATE.md
  docs/releases_thunderdome.md
Labels: skip/changelog

#10516 chore: switch back to release helia-interop
  .github/workflows/interop.yml
Labels: skip/changelog

#10517 docs(config): improve profile descriptions
  config/profile.go
  docs/config.md
  docs/datastores.md
Labels: skip/changelog

#10523 feat: use ipfs-webui@4.3.2
  core/corehttp/webui.go
Labels: status/blocked, skip/changelog

#10518 chore: clarify dep update in RELEASE_CHECKLIST.md
  docs/RELEASE_CHECKLIST.md
Labels: skip/changelog

#10525 docs: clarify Gateway.PublicGateways
  docs/config.md
Labels: skip/changelog

#10506 refactor: simplify logic for MFS remote pinning
  cmd/ipfs/kubo/daemon.go
  cmd/ipfs/kubo/pinmfs.go
  cmd/ipfs/kubo/pinmfs_test.go
  core/commands/pin/remotepin.go
Labels: skip/changelog

#10512 feat(bitswap): allow configuring WithWantHaveReplaceSize
  config/internal.go
  core/node/bitswap.go
  docs/examples/kubo-as-a-library/go.mod
  docs/examples/kubo-as-a-library/go.sum
  go.mod
  go.sum
  test/dependencies/go.mod
  test/dependencies/go.sum
Labels: skip/changelog

#10492 [skip changelog]Fix issue in ResourceManager and nopfsPlugin about repo path
  core/node/groups.go
  core/node/libp2p/rcmgr.go
  plugin/plugins/nopfs/nopfs.go
  repo/mock.go
  repo/repo.go
Labels: P1
