Repository ipfs/kubo, pull requests merged in 2025-04, with the labels that each got.

#10771 docs: Fix typo in v0.34 changelog [skip changelog]
  docs/changelogs/v0.34.md
Labels: kind/nonfunctional

#10768 docs: known issues with file/urlstores
  docs/experimental-features.md
Labels: skip/changelog

#10791 docs(fuse): use latest package name
  docs/fuse.md
Labels: topic/docs, skip/changelog
